framework:
    workflows:
        materiel_lifecycle:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'statut'
            supports:
                - App\Entity\MaterielEtMaintenance\Materiel
            initial_marking: en_service
            places:
                - en_service
                - panne_signalee
                - attente_planification
                - en_maintenance
                - en_vente
                - reforme
            transitions:
                mettre_en_maintenance:
                    from: en_service
                    to:   panne_signalee
                demander_planification:
                    from: panne_signalee
                    to:   attente_planification
                valider_maintenance:
                    from: [panne_signalee, attente_planification]
                    to:   en_maintenance
                confirmer_maintenance:
                    from: [en_maintenance, panne_signalee, attente_planification]
                    to:   en_service
                mettre_en_vente:
                    from: en_service
                    to:   en_vente
                reformer:
                    from: [en_service, panne_signalee, attente_planification]
                    to:   reforme

