<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260419123858 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alerte_technicien (id INT AUTO_INCREMENT NOT NULL, description LONGTEXT NOT NULL, date_signalement DATETIME NOT NULL, statut VARCHAR(20) NOT NULL, id_materiel INT NOT NULL, agriculteur_id INT NOT NULL, INDEX IDX_8D2FDFED48095C04 (id_materiel), INDEX IDX_8D2FDFED7EBB810E (agriculteur_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE notificationMaintenance (id INT AUTO_INCREMENT NOT NULL, nouveau_statut VARCHAR(50) DEFAULT NULL, titre VARCHAR(255) DEFAULT NULL, message LONGTEXT DEFAULT NULL, is_read TINYINT DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, user_id INT NOT NULL, materiel_id INT DEFAULT NULL, INDEX IDX_31212264A76ED395 (user_id), INDEX IDX_3121226416880AAF (materiel_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE reclamation_materiel (id INT AUTO_INCREMENT NOT NULL, sujet VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, urgence VARCHAR(20) DEFAULT \'normale\' NOT NULL, statut VARCHAR(30) DEFAULT \'en_attente\' NOT NULL, commentaire_admin LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, user_id INT NOT NULL, materiel_id INT DEFAULT NULL, INDEX IDX_9F0B399DA76ED395 (user_id), INDEX IDX_9F0B399D16880AAF (materiel_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE alerte_technicien ADD CONSTRAINT FK_8D2FDFED48095C04 FOREIGN KEY (id_materiel) REFERENCES materiel (id_materiel)');
        $this->addSql('ALTER TABLE alerte_technicien ADD CONSTRAINT FK_8D2FDFED7EBB810E FOREIGN KEY (agriculteur_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE notificationMaintenance ADD CONSTRAINT FK_31212264A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notificationMaintenance ADD CONSTRAINT FK_3121226416880AAF FOREIGN KEY (materiel_id) REFERENCES materiel (id_materiel) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE reclamation_materiel ADD CONSTRAINT FK_9F0B399DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reclamation_materiel ADD CONSTRAINT FK_9F0B399D16880AAF FOREIGN KEY (materiel_id) REFERENCES materiel (id_materiel) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE chatbot_conversation DROP FOREIGN KEY `chatbot_conversation_ibfk_1`');
        $this->addSql('ALTER TABLE employe_competence DROP FOREIGN KEY `employe_competence_ibfk_1`');
        $this->addSql('ALTER TABLE notification_config DROP FOREIGN KEY `notification_config_ibfk_1`');
        $this->addSql('ALTER TABLE review_comments DROP FOREIGN KEY `FK_rc_parent`');
        $this->addSql('ALTER TABLE review_comments DROP FOREIGN KEY `FK_rc_participation`');
        $this->addSql('ALTER TABLE review_comments DROP FOREIGN KEY `FK_rc_user`');
        $this->addSql('ALTER TABLE tache_competence_requise DROP FOREIGN KEY `tache_competence_requise_ibfk_1`');
        $this->addSql('DROP TABLE chatbot_conversation');
        $this->addSql('DROP TABLE employe_competence');
        $this->addSql('DROP TABLE notification_config');
        $this->addSql('DROP TABLE review_comments');
        $this->addSql('DROP TABLE tache_competence_requise');
        $this->addSql('ALTER TABLE abonnement DROP FOREIGN KEY `fk_abonnement_offre`');
        $this->addSql('ALTER TABLE abonnement CHANGE type type VARCHAR(100) DEFAULT NULL, CHANGE prix prix DOUBLE PRECISION NOT NULL, CHANGE date_debut date_debut DATE DEFAULT NULL, CHANGE date_fin date_fin DATE DEFAULT NULL, CHANGE statut statut VARCHAR(50) DEFAULT \'ACTIF\', CHANGE user_id user_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE abonnement ADD CONSTRAINT FK_351268BB4CC8505A FOREIGN KEY (offre_id) REFERENCES offre (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE abonnement RENAME INDEX fk_user_abonnement TO IDX_351268BBA76ED395');
        $this->addSql('ALTER TABLE abonnement RENAME INDEX fk_abonnement_offre TO IDX_351268BB4CC8505A');
        $this->addSql('ALTER TABLE avis ADD isVerifiedBuyer TINYINT DEFAULT 0 NOT NULL, CHANGE commentaire commentaire LONGTEXT DEFAULT NULL, CHANGE dateAvis dateAvis DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT FK_8F91ABF0FE6E88D7 FOREIGN KEY (idUser) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT FK_8F91ABF0391C87D5 FOREIGN KEY (idProduit) REFERENCES produits (idProduit) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE avis RENAME INDEX fk_avis_user TO IDX_8F91ABF0FE6E88D7');
        $this->addSql('ALTER TABLE avis RENAME INDEX fk_avis_produit TO IDX_8F91ABF0391C87D5');
        $this->addSql('ALTER TABLE badge CHANGE condition_type condition_type ENUM(\'DIAGNOSTIC\',\'POINTS\',\'HEALTHY_PLANTS\',\'SOLUTION\') DEFAULT \'DIAGNOSTIC\'');
        $this->addSql('ALTER TABLE commande ADD qr_code_token VARCHAR(255) DEFAULT NULL, ADD qr_code_path VARCHAR(255) DEFAULT NULL, CHANGE total total DOUBLE PRECISION DEFAULT 0 NOT NULL, CHANGE frais_livraison frais_livraison DOUBLE PRECISION DEFAULT 0 NOT NULL, CHANGE montantRemise montantRemise DOUBLE PRECISION DEFAULT 0 NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6EEAA67D1BC9050B ON commande (qr_code_token)');
        $this->addSql('ALTER TABLE community_analytics_daily DROP FOREIGN KEY `FK_9F2CCBDE4B89032C`');
        $this->addSql('ALTER TABLE community_analytics_daily ADD CONSTRAINT FK_99006B174B89032C FOREIGN KEY (post_id) REFERENCES community_posts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE community_analytics_daily RENAME INDEX idx_9f2ccbde4b89032c TO IDX_99006B174B89032C');
        $this->addSql('ALTER TABLE community_comments CHANGE content content LONGTEXT NOT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE community_comments RENAME INDEX post_id TO IDX_ADD8530D4B89032C');
        $this->addSql('ALTER TABLE community_comments RENAME INDEX user_id TO IDX_ADD8530DA76ED395');
        $this->addSql('ALTER TABLE community_comments RENAME INDEX fk_parent_comment TO IDX_ADD8530DBF2AF943');
        $this->addSql('ALTER TABLE community_likes CHANGE vote_type vote_type ENUM(\'LIKE\',\'DISLIKE\') NOT NULL DEFAULT \'LIKE\', CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE community_likes RENAME INDEX post_id TO IDX_32BA34394B89032C');
        $this->addSql('ALTER TABLE community_likes RENAME INDEX comment_id TO IDX_32BA3439F8697D13');
        $this->addSql('ALTER TABLE community_posts CHANGE description description LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE community_posts ADD CONSTRAINT FK_F32DC0BEE50890C4 FOREIGN KEY (solution_comment_id) REFERENCES community_comments (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_F32DC0BEE50890C4 ON community_posts (solution_comment_id)');
        $this->addSql('ALTER TABLE community_posts RENAME INDEX user_id TO IDX_F32DC0BEA76ED395');
        $this->addSql('ALTER TABLE community_reports DROP FOREIGN KEY `FK_report_reporter`');
        $this->addSql('ALTER TABLE community_reports CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE community_reports ADD CONSTRAINT FK_D5DACE16E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE community_reports RENAME INDEX idx_reporter TO IDX_D5DACE16E1CFE6F5');
        $this->addSql('ALTER TABLE community_reports RENAME INDEX idx_post TO IDX_D5DACE164B89032C');
        $this->addSql('ALTER TABLE community_reports RENAME INDEX idx_comment TO IDX_D5DACE16F8697D13');
        $this->addSql('ALTER TABLE coupon CHANGE typeReduction typeReduction ENUM(\'POURCENTAGE\', \'FIXE\') NOT NULL, CHANGE montantMin montantMin DOUBLE PRECISION DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE diag_notification CHANGE is_read is_read TINYINT NOT NULL');
        $this->addSql('ALTER TABLE diag_notification RENAME INDEX idx_diag_notif_user TO IDX_D596EB26A76ED395');
        $this->addSql('ALTER TABLE diagnostic CHANGE date_scan date_scan DATETIME DEFAULT NULL, CHANGE confiance confiance DOUBLE PRECISION DEFAULT 0, CHANGE user_id user_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE diagnostic RENAME INDEX fk_diagnostic_user TO IDX_FA7C8889A76ED395');
        $this->addSql('DROP INDEX qr_code_unique ON employe');
        $this->addSql('ALTER TABLE evenement DROP FOREIGN KEY `evenement_ibfk_1`');
        $this->addSql('ALTER TABLE evenement_favoris DROP FOREIGN KEY `evenement_favoris_ibfk_1`');
        $this->addSql('ALTER TABLE evenement_favoris DROP FOREIGN KEY `evenement_favoris_ibfk_2`');
        $this->addSql('ALTER TABLE farm_health_report CHANGE llava_analysis llava_analysis LONGTEXT DEFAULT NULL, CHANGE generated_at generated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE farm_health_report RENAME INDEX scan_id TO IDX_5D3720A82827AAD3');
        $this->addSql('ALTER TABLE farm_health_scan CHANGE concerns concerns LONGTEXT DEFAULT NULL, CHANGE scan_date scan_date DATETIME DEFAULT NULL, CHANGE status status ENUM(\'PENDING\',\'PROCESSING\',\'COMPLETED\',\'FAILED\') DEFAULT \'PENDING\'');
        $this->addSql('ALTER TABLE farm_health_scan RENAME INDEX user_id TO IDX_C32EEC75A76ED395');
        $this->addSql('ALTER TABLE maintenance DROP FOREIGN KEY `fk_maintenance_materiel`');
        $this->addSql('ALTER TABLE maintenance ADD decision_admin VARCHAR(50) DEFAULT NULL, CHANGE date_maintenance date_maintenance DATETIME NOT NULL');
        $this->addSql('ALTER TABLE materiel DROP FOREIGN KEY `fk_materiel_user`');
        $this->addSql('DROP INDEX fk_materiel_user ON materiel');
        $this->addSql('ALTER TABLE materiel ADD qr_code_token VARCHAR(255) DEFAULT NULL, ADD qr_code_path VARCHAR(255) DEFAULT NULL, ADD statut VARCHAR(50) NOT NULL, ADD heures_utilisation INT NOT NULL, ADD seuil_maintenance_heures INT NOT NULL, ADD derniere_maintenance_heures INT NOT NULL, DROP frequence_maintenance_mois, CHANGE google_calendar_event_id prochaine_maintenance_alerte VARCHAR(255) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_18D2B0911BC9050B ON materiel (qr_code_token)');
        $this->addSql('ALTER TABLE moderation_audit DROP FOREIGN KEY `FK_audit_moderator`');
        $this->addSql('ALTER TABLE moderation_audit DROP FOREIGN KEY `FK_audit_target`');
        $this->addSql('ALTER TABLE moderation_audit CHANGE action action VARCHAR(50) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE moderation_audit ADD CONSTRAINT FK_614218EDD0AFA354 FOREIGN KEY (moderator_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE moderation_audit ADD CONSTRAINT FK_614218ED6C066AFE FOREIGN KEY (target_user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE moderation_audit RENAME INDEX idx_moderator TO IDX_614218EDD0AFA354');
        $this->addSql('ALTER TABLE moderation_audit RENAME INDEX idx_target TO IDX_614218ED6C066AFE');
        $this->addSql('ALTER TABLE notif_market CHANGE message message LONGTEXT NOT NULL, CHANGE lue lue TINYINT DEFAULT 0 NOT NULL, CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE notif_market ADD CONSTRAINT FK_6F8F1D906B3CA4B FOREIGN KEY (id_user) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notif_market ADD CONSTRAINT FK_6F8F1D90F7384557 FOREIGN KEY (id_produit) REFERENCES produits (idProduit) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE notif_market ADD CONSTRAINT FK_6F8F1D903E314AE8 FOREIGN KEY (id_commande) REFERENCES commande (idCommande) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE notif_market RENAME INDEX id_user TO IDX_6F8F1D906B3CA4B');
        $this->addSql('ALTER TABLE notif_market RENAME INDEX id_produit TO IDX_6F8F1D90F7384557');
        $this->addSql('ALTER TABLE notif_market RENAME INDEX id_commande TO IDX_6F8F1D903E314AE8');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY `notification_ibfk_1`');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY `notification_ibfk_2`');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY `notification_ibfk_3`');
        $this->addSql('DROP INDEX notification_ibfk_2 ON notification');
        $this->addSql('DROP INDEX notification_ibfk_3 ON notification');
        $this->addSql('ALTER TABLE offre CHANGE prix_mensuel prix_mensuel DOUBLE PRECISION NOT NULL, CHANGE avantages avantages LONGTEXT DEFAULT NULL, CHANGE couleur_primaire couleur_primaire VARCHAR(20) DEFAULT \'#6B7F3F\', CHANGE couleur_secondaire couleur_secondaire VARCHAR(20) DEFAULT \'#4A5A2B\', CHANGE date_creation date_creation DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE panier CHANGE totalMontant totalMontant DOUBLE PRECISION DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE parcelle CHANGE surface surface NUMERIC(10, 2) NOT NULL, CHANGE localisation localisation VARCHAR(255) NOT NULL, CHANGE type_sol type_sol VARCHAR(100) NOT NULL, CHANGE systeme_irrigation systeme_irrigation VARCHAR(100) NOT NULL, CHANGE statut statut VARCHAR(50) DEFAULT \'active\' NOT NULL, CHANGE agriculteur_id agriculteur_id INT NOT NULL, CHANGE latitude latitude NUMERIC(10, 6) DEFAULT NULL, CHANGE longitude longitude NUMERIC(10, 6) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE parcelle RENAME INDEX fk_parcelle_agriculteur TO IDX_C56E2CF67EBB810E');
        $this->addSql('ALTER TABLE participation DROP FOREIGN KEY `participation_ibfk_1`');
        $this->addSql('ALTER TABLE participation DROP FOREIGN KEY `participation_ibfk_2`');
        $this->addSql('ALTER TABLE prevention_plan DROP FOREIGN KEY `prevention_plan_ibfk_2`');
        $this->addSql('ALTER TABLE prevention_plan CHANGE problem_summary problem_summary LONGTEXT DEFAULT NULL, CHANGE steps steps LONGTEXT NOT NULL, CHANGE estimated_cost estimated_cost DOUBLE PRECISION DEFAULT NULL, CHANGE expected_outcome expected_outcome LONGTEXT DEFAULT NULL, CHANGE impact_level impact_level ENUM(\'HIGH\',\'MEDIUM\',\'LOW\'), CHANGE status status ENUM(\'ACTIVE\',\'COMPLETED\',\'ABANDONED\') DEFAULT \'ACTIVE\', CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE prevention_plan ADD CONSTRAINT FK_873E4A5772897D8B FOREIGN KEY (vulnerability_id) REFERENCES vulnerability (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE prevention_plan RENAME INDEX report_id TO IDX_873E4A574BD2A4C0');
        $this->addSql('ALTER TABLE prevention_plan RENAME INDEX vulnerability_id TO IDX_873E4A5772897D8B');
        $this->addSql('ALTER TABLE prevention_task CHANGE status status ENUM(\'PENDING\',\'COMPLETED\',\'MISSED\') DEFAULT \'PENDING\'');
        $this->addSql('ALTER TABLE prevention_task RENAME INDEX prevention_plan_id TO IDX_81ACA0FC44547A6');
        $this->addSql('ALTER TABLE produits ADD materiel_id INT DEFAULT NULL, CHANGE uniteMesure uniteMesure ENUM(\'Kg\',\'L\',\'Piece\') NOT NULL, CHANGE remise remise DOUBLE PRECISION DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE produits ADD CONSTRAINT FK_BE2DDF8C16880AAF FOREIGN KEY (materiel_id) REFERENCES materiel (id_materiel)');
        $this->addSql('CREATE INDEX IDX_BE2DDF8C16880AAF ON produits (materiel_id)');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY `review_ibfk_2`');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY `review_ibfk_3`');
        $this->addSql('ALTER TABLE review CHANGE review_type review_type ENUM(\'DIAGNOSIS\',\'PROGRESS\',\'PREVENTION\') NOT NULL, CHANGE status status ENUM(\'PENDING\',\'IN_PROGRESS\',\'COMPLETED\') DEFAULT \'PENDING\', CHANGE ai_analysis ai_analysis LONGTEXT DEFAULT NULL, CHANGE expert_notes expert_notes LONGTEXT DEFAULT NULL, CHANGE expert_verdict expert_verdict ENUM(\'CONTINUE\',\'HEALED\',\'WORSENED\'), CHANGE farmer_response farmer_response ENUM(\'ACCEPTED\',\'REJECTED\',\'ACKNOWLEDGED\'), CHANGE ai_proposed_plan ai_proposed_plan LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6905FC057 FOREIGN KEY (treatment_plan_id) REFERENCES treatment_plan (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6C5568CE4 FOREIGN KEY (expert_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6C44547A6 FOREIGN KEY (prevention_plan_id) REFERENCES prevention_plan (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_794381C6C44547A6 ON review (prevention_plan_id)');
        $this->addSql('ALTER TABLE review RENAME INDEX diagnostic_id TO IDX_794381C6224CCA91');
        $this->addSql('ALTER TABLE review RENAME INDEX treatment_plan_id TO IDX_794381C6905FC057');
        $this->addSql('ALTER TABLE review RENAME INDEX expert_id TO IDX_794381C6C5568CE4');
        $this->addSql('ALTER TABLE traitement CHANGE description_detaillee description_detaillee LONGTEXT DEFAULT NULL, CHANGE type_traitement type_traitement ENUM(\'FONGICIDE\',\'HERBICIDE\',\'INSECTICIDE\',\'BACTERICIDE\',\'NEMATICIDE\',\'VIRUCIDE\',\'NUTRIMENT\',\'REGULATEUR_CROISSANCE\',\'AUTRE\') DEFAULT \'AUTRE\'');
        $this->addSql('ALTER TABLE traitement ADD CONSTRAINT FK_2A356D27224CCA91 FOREIGN KEY (diagnostic_id) REFERENCES diagnostic (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_2A356D27224CCA91 ON traitement (diagnostic_id)');
        $this->addSql('ALTER TABLE treatment_plan CHANGE start_date start_date DATETIME DEFAULT NULL, CHANGE status status ENUM(\'ACTIVE\',\'COMPLETED\',\'ABANDONED\') DEFAULT \'ACTIVE\'');
        $this->addSql('ALTER TABLE treatment_plan RENAME INDEX diagnostic_id TO IDX_1E99976C224CCA91');
        $this->addSql('ALTER TABLE treatment_task CHANGE status status ENUM(\'PENDING\',\'COMPLETED\',\'MISSED\') DEFAULT \'PENDING\', CHANGE tech_x tech_x DOUBLE PRECISION DEFAULT NULL, CHANGE tech_y tech_y DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE treatment_task RENAME INDEX treatment_plan_id TO IDX_91BD1734905FC057');
        $this->addSql('ALTER TABLE user CHANGE role role ENUM(\'ADMIN\',\'AGRICULTEUR\',\'CLIENT\',\'AGRONOME\') NOT NULL DEFAULT \'AGRICULTEUR\', CHANGE points points INT DEFAULT 0 NOT NULL, CHANGE level level INT DEFAULT 1 NOT NULL, CHANGE two_factor_enabled two_factor_enabled TINYINT DEFAULT 0 NOT NULL, CHANGE fingerprint_signature fingerprint_signature LONGTEXT DEFAULT NULL, CHANGE points_fidelite points_fidelite DOUBLE PRECISION DEFAULT 0 NOT NULL, CHANGE reset_password_code reset_password_code VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE user_badge DROP FOREIGN KEY `user_badge_ibfk_1`');
        $this->addSql('ALTER TABLE user_badge DROP FOREIGN KEY `user_badge_ibfk_2`');
        $this->addSql('ALTER TABLE user_badge CHANGE acquired_at acquired_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345F7A2C2FC FOREIGN KEY (badge_id) REFERENCES badge (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_badge RENAME INDEX badge_id TO IDX_1C32B345F7A2C2FC');
        $this->addSql('ALTER TABLE user_blocks RENAME INDEX idx_user_blocks_source TO IDX_ABBF8E453AD8644E');
        $this->addSql('ALTER TABLE user_blocks RENAME INDEX idx_user_blocks_target TO IDX_ABBF8E45233D34C1');
        $this->addSql('ALTER TABLE vulnerability CHANGE type type ENUM(\'PEST_OUTBREAK_RISK\',\'DISEASE_RISK\',\'NUTRIENT_DEFICIENCY\',\'LOW_POLLINATION\',\'SOIL_DEGRADATION\') NOT NULL, CHANGE severity severity ENUM(\'CRITICAL\',\'MEDIUM\',\'LOW\') NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE risk_score risk_score DOUBLE PRECISION DEFAULT NULL, CHANGE estimated_cost_if_occurs estimated_cost_if_occurs DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE vulnerability RENAME INDEX report_id TO IDX_6C4E40474BD2A4C0');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE chatbot_conversation (id_conversation INT AUTO_INCREMENT NOT NULL, id_utilisateur INT NOT NULL, message_utilisateur TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, reponse_chatbot TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, intention VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, contexte LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, satisfaction INT DEFAULT NULL, date_message DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_utilisateur (id_utilisateur), INDEX idx_intention (intention), INDEX idx_date (date_message), PRIMARY KEY (id_conversation)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE employe_competence (id INT AUTO_INCREMENT NOT NULL, id_employe INT NOT NULL, id_competence INT NOT NULL, niveau INT DEFAULT 1 NOT NULL, annees_experience NUMERIC(3, 1) DEFAULT \'0.0\', derniere_utilisation DATE DEFAULT NULL, certification VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, notes TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, date_ajout DATETIME DEFAULT CURRENT_TIMESTAMP, date_modification DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX unique_employe_competence (id_employe, id_competence), INDEX id_competence (id_competence), INDEX idx_niveau (niveau), INDEX idx_experience (annees_experience), INDEX IDX_161DB2B826997AC9 (id_employe), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE notification_config (id_config INT AUTO_INCREMENT NOT NULL, id_agriculteur INT NOT NULL, seuil_taches_employe INT DEFAULT 10, seuil_jours_inactivite INT DEFAULT 30, activer_notifications TINYINT DEFAULT 1, activer_sons TINYINT DEFAULT 1, UNIQUE INDEX id_agriculteur (id_agriculteur), PRIMARY KEY (id_config)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE review_comments (id INT AUTO_INCREMENT NOT NULL, content LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, created_at DATETIME NOT NULL, participation_id INT NOT NULL, user_id INT NOT NULL, parent_comment_id INT DEFAULT NULL, INDEX IDX_participation (participation_id), INDEX IDX_user (user_id), INDEX IDX_parent (parent_comment_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE tache_competence_requise (id INT AUTO_INCREMENT NOT NULL, id_tache INT NOT NULL, id_competence INT NOT NULL, niveau_requis INT DEFAULT 2 NOT NULL, importance INT DEFAULT 5, date_ajout DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX unique_tache_competence (id_tache, id_competence), INDEX id_competence (id_competence), INDEX idx_niveau (niveau_requis), INDEX idx_importance (importance), INDEX IDX_FEBDEA6A7D026145 (id_tache), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE chatbot_conversation ADD CONSTRAINT `chatbot_conversation_ibfk_1` FOREIGN KEY (id_utilisateur) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employe_competence ADD CONSTRAINT `employe_competence_ibfk_1` FOREIGN KEY (id_employe) REFERENCES employe (id_employe) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification_config ADD CONSTRAINT `notification_config_ibfk_1` FOREIGN KEY (id_agriculteur) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE review_comments ADD CONSTRAINT `FK_rc_parent` FOREIGN KEY (parent_comment_id) REFERENCES review_comments (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE review_comments ADD CONSTRAINT `FK_rc_participation` FOREIGN KEY (participation_id) REFERENCES participation (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE review_comments ADD CONSTRAINT `FK_rc_user` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tache_competence_requise ADD CONSTRAINT `tache_competence_requise_ibfk_1` FOREIGN KEY (id_tache) REFERENCES tache (id_tache) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE alerte_technicien DROP FOREIGN KEY FK_8D2FDFED48095C04');
        $this->addSql('ALTER TABLE alerte_technicien DROP FOREIGN KEY FK_8D2FDFED7EBB810E');
        $this->addSql('ALTER TABLE notificationMaintenance DROP FOREIGN KEY FK_31212264A76ED395');
        $this->addSql('ALTER TABLE notificationMaintenance DROP FOREIGN KEY FK_3121226416880AAF');
        $this->addSql('ALTER TABLE reclamation_materiel DROP FOREIGN KEY FK_9F0B399DA76ED395');
        $this->addSql('ALTER TABLE reclamation_materiel DROP FOREIGN KEY FK_9F0B399D16880AAF');
        $this->addSql('DROP TABLE alerte_technicien');
        $this->addSql('DROP TABLE notificationMaintenance');
        $this->addSql('DROP TABLE reclamation_materiel');
        $this->addSql('ALTER TABLE abonnement DROP FOREIGN KEY FK_351268BB4CC8505A');
        $this->addSql('ALTER TABLE abonnement CHANGE type type VARCHAR(50) NOT NULL, CHANGE prix prix FLOAT NOT NULL, CHANGE date_debut date_debut DATE NOT NULL, CHANGE date_fin date_fin DATE NOT NULL, CHANGE statut statut VARCHAR(20) DEFAULT \'ACTIF\', CHANGE user_id user_id INT NOT NULL');
        $this->addSql('ALTER TABLE abonnement ADD CONSTRAINT `fk_abonnement_offre` FOREIGN KEY (offre_id) REFERENCES offre (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE abonnement RENAME INDEX idx_351268bba76ed395 TO fk_user_abonnement');
        $this->addSql('ALTER TABLE abonnement RENAME INDEX idx_351268bb4cc8505a TO fk_abonnement_offre');
        $this->addSql('ALTER TABLE avis DROP FOREIGN KEY FK_8F91ABF0FE6E88D7');
        $this->addSql('ALTER TABLE avis DROP FOREIGN KEY FK_8F91ABF0391C87D5');
        $this->addSql('ALTER TABLE avis DROP isVerifiedBuyer, CHANGE commentaire commentaire TEXT DEFAULT NULL, CHANGE dateAvis dateAvis DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE avis RENAME INDEX idx_8f91abf0fe6e88d7 TO fk_avis_user');
        $this->addSql('ALTER TABLE avis RENAME INDEX idx_8f91abf0391c87d5 TO fk_avis_produit');
        $this->addSql('ALTER TABLE badge CHANGE condition_type condition_type ENUM(\'DIAGNOSTIC\', \'POINTS\', \'HEALTHY_PLANTS\', \'SOLUTION\') DEFAULT \'DIAGNOSTIC\'');
        $this->addSql('DROP INDEX UNIQ_6EEAA67D1BC9050B ON commande');
        $this->addSql('ALTER TABLE commande DROP qr_code_token, DROP qr_code_path, CHANGE total total DOUBLE PRECISION DEFAULT \'0\' NOT NULL, CHANGE frais_livraison frais_livraison DOUBLE PRECISION DEFAULT \'0\' NOT NULL, CHANGE montantRemise montantRemise DOUBLE PRECISION DEFAULT \'0\' NOT NULL');
        $this->addSql('ALTER TABLE community_analytics_daily DROP FOREIGN KEY FK_99006B174B89032C');
        $this->addSql('ALTER TABLE community_analytics_daily ADD CONSTRAINT `FK_9F2CCBDE4B89032C` FOREIGN KEY (post_id) REFERENCES community_posts (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE community_analytics_daily RENAME INDEX idx_99006b174b89032c TO IDX_9F2CCBDE4B89032C');
        $this->addSql('ALTER TABLE community_comments CHANGE content content TEXT NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE community_comments RENAME INDEX idx_add8530d4b89032c TO post_id');
        $this->addSql('ALTER TABLE community_comments RENAME INDEX idx_add8530da76ed395 TO user_id');
        $this->addSql('ALTER TABLE community_comments RENAME INDEX idx_add8530dbf2af943 TO fk_parent_comment');
        $this->addSql('ALTER TABLE community_likes CHANGE vote_type vote_type ENUM(\'LIKE\', \'DISLIKE\') DEFAULT \'LIKE\' NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE community_likes RENAME INDEX idx_32ba34394b89032c TO post_id');
        $this->addSql('ALTER TABLE community_likes RENAME INDEX idx_32ba3439f8697d13 TO comment_id');
        $this->addSql('ALTER TABLE community_posts DROP FOREIGN KEY FK_F32DC0BEE50890C4');
        $this->addSql('DROP INDEX IDX_F32DC0BEE50890C4 ON community_posts');
        $this->addSql('ALTER TABLE community_posts CHANGE description description TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE community_posts RENAME INDEX idx_f32dc0bea76ed395 TO user_id');
        $this->addSql('ALTER TABLE community_reports DROP FOREIGN KEY FK_D5DACE16E1CFE6F5');
        $this->addSql('ALTER TABLE community_reports CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE community_reports ADD CONSTRAINT `FK_report_reporter` FOREIGN KEY (reporter_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE community_reports RENAME INDEX idx_d5dace16e1cfe6f5 TO IDX_reporter');
        $this->addSql('ALTER TABLE community_reports RENAME INDEX idx_d5dace164b89032c TO IDX_post');
        $this->addSql('ALTER TABLE community_reports RENAME INDEX idx_d5dace16f8697d13 TO IDX_comment');
        $this->addSql('ALTER TABLE coupon CHANGE typeReduction typeReduction ENUM(\'POURCENTAGE\', \'FIXE\') NOT NULL, CHANGE montantMin montantMin DOUBLE PRECISION DEFAULT \'0\' NOT NULL');
        $this->addSql('ALTER TABLE diag_notification CHANGE is_read is_read TINYINT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE diag_notification RENAME INDEX idx_d596eb26a76ed395 TO IDX_DIAG_NOTIF_USER');
        $this->addSql('ALTER TABLE diagnostic CHANGE date_scan date_scan DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE confiance confiance FLOAT DEFAULT NULL, CHANGE user_id user_id INT NOT NULL');
        $this->addSql('ALTER TABLE diagnostic RENAME INDEX idx_fa7c8889a76ed395 TO fk_diagnostic_user');
        $this->addSql('CREATE UNIQUE INDEX qr_code_unique ON employe (qr_code_unique)');
        $this->addSql('ALTER TABLE evenement ADD CONSTRAINT `evenement_ibfk_1` FOREIGN KEY (id_createur) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evenement_favoris ADD CONSTRAINT `evenement_favoris_ibfk_1` FOREIGN KEY (id_evenement) REFERENCES evenement (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evenement_favoris ADD CONSTRAINT `evenement_favoris_ibfk_2` FOREIGN KEY (id_utilisateur) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE farm_health_report CHANGE llava_analysis llava_analysis TEXT DEFAULT NULL, CHANGE generated_at generated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE farm_health_report RENAME INDEX idx_5d3720a82827aad3 TO scan_id');
        $this->addSql('ALTER TABLE farm_health_scan CHANGE concerns concerns TEXT DEFAULT NULL, CHANGE scan_date scan_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE status status ENUM(\'PENDING\', \'PROCESSING\', \'COMPLETED\', \'FAILED\') DEFAULT \'PENDING\'');
        $this->addSql('ALTER TABLE farm_health_scan RENAME INDEX idx_c32eec75a76ed395 TO user_id');
        $this->addSql('ALTER TABLE maintenance DROP decision_admin, CHANGE date_maintenance date_maintenance DATE NOT NULL');
        $this->addSql('ALTER TABLE maintenance ADD CONSTRAINT `fk_maintenance_materiel` FOREIGN KEY (materiel_id) REFERENCES materiel (id_materiel) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX UNIQ_18D2B0911BC9050B ON materiel');
        $this->addSql('ALTER TABLE materiel ADD google_calendar_event_id VARCHAR(255) DEFAULT NULL, ADD frequence_maintenance_mois INT DEFAULT 12, DROP prochaine_maintenance_alerte, DROP qr_code_token, DROP qr_code_path, DROP statut, DROP heures_utilisation, DROP seuil_maintenance_heures, DROP derniere_maintenance_heures');
        $this->addSql('ALTER TABLE materiel ADD CONSTRAINT `fk_materiel_user` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE INDEX fk_materiel_user ON materiel (user_id)');
        $this->addSql('ALTER TABLE moderation_audit DROP FOREIGN KEY FK_614218EDD0AFA354');
        $this->addSql('ALTER TABLE moderation_audit DROP FOREIGN KEY FK_614218ED6C066AFE');
        $this->addSql('ALTER TABLE moderation_audit CHANGE action action VARCHAR(50) NOT NULL COMMENT \'MUTE, BAN, UNBAN, UNMUTE, DELETE_POST, DELETE_COMMENT, GRANT_MOD, REVOKE_MOD\', CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE moderation_audit ADD CONSTRAINT `FK_audit_moderator` FOREIGN KEY (moderator_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE moderation_audit ADD CONSTRAINT `FK_audit_target` FOREIGN KEY (target_user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE moderation_audit RENAME INDEX idx_614218edd0afa354 TO IDX_moderator');
        $this->addSql('ALTER TABLE moderation_audit RENAME INDEX idx_614218ed6c066afe TO IDX_target');
        $this->addSql('ALTER TABLE notif_market DROP FOREIGN KEY FK_6F8F1D906B3CA4B');
        $this->addSql('ALTER TABLE notif_market DROP FOREIGN KEY FK_6F8F1D90F7384557');
        $this->addSql('ALTER TABLE notif_market DROP FOREIGN KEY FK_6F8F1D903E314AE8');
        $this->addSql('ALTER TABLE notif_market CHANGE message message TEXT NOT NULL, CHANGE lue lue TINYINT DEFAULT 0, CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE notif_market RENAME INDEX idx_6f8f1d906b3ca4b TO id_user');
        $this->addSql('ALTER TABLE notif_market RENAME INDEX idx_6f8f1d90f7384557 TO id_produit');
        $this->addSql('ALTER TABLE notif_market RENAME INDEX idx_6f8f1d903e314ae8 TO id_commande');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT `notification_ibfk_1` FOREIGN KEY (id_agriculteur) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT `notification_ibfk_2` FOREIGN KEY (id_tache) REFERENCES tache (id_tache) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT `notification_ibfk_3` FOREIGN KEY (id_employe) REFERENCES employe (id_employe) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('CREATE INDEX notification_ibfk_2 ON notification (id_tache)');
        $this->addSql('CREATE INDEX notification_ibfk_3 ON notification (id_employe)');
        $this->addSql('ALTER TABLE offre CHANGE prix_mensuel prix_mensuel FLOAT NOT NULL, CHANGE avantages avantages TEXT DEFAULT NULL, CHANGE couleur_primaire couleur_primaire VARCHAR(20) DEFAULT NULL, CHANGE couleur_secondaire couleur_secondaire VARCHAR(20) DEFAULT NULL, CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE panier CHANGE totalMontant totalMontant DOUBLE PRECISION DEFAULT \'0\' NOT NULL');
        $this->addSql('ALTER TABLE parcelle CHANGE surface surface DOUBLE PRECISION NOT NULL, CHANGE localisation localisation VARCHAR(255) DEFAULT NULL, CHANGE type_sol type_sol VARCHAR(255) DEFAULT NULL, CHANGE systeme_irrigation systeme_irrigation VARCHAR(255) DEFAULT NULL, CHANGE statut statut VARCHAR(50) DEFAULT \'active\', CHANGE latitude latitude DOUBLE PRECISION DEFAULT NULL, CHANGE longitude longitude DOUBLE PRECISION DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE agriculteur_id agriculteur_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE parcelle RENAME INDEX idx_c56e2cf67ebb810e TO fk_parcelle_agriculteur');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT `participation_ibfk_1` FOREIGN KEY (id_evenement) REFERENCES evenement (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT `participation_ibfk_2` FOREIGN KEY (id_utilisateur) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE prevention_plan DROP FOREIGN KEY FK_873E4A5772897D8B');
        $this->addSql('ALTER TABLE prevention_plan CHANGE problem_summary problem_summary TEXT DEFAULT NULL, CHANGE steps steps TEXT NOT NULL, CHANGE estimated_cost estimated_cost FLOAT DEFAULT NULL, CHANGE expected_outcome expected_outcome TEXT DEFAULT NULL, CHANGE impact_level impact_level ENUM(\'HIGH\', \'MEDIUM\', \'LOW\') DEFAULT NULL, CHANGE status status ENUM(\'ACTIVE\', \'COMPLETED\', \'ABANDONED\') DEFAULT \'ACTIVE\', CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE prevention_plan ADD CONSTRAINT `prevention_plan_ibfk_2` FOREIGN KEY (vulnerability_id) REFERENCES vulnerability (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE prevention_plan RENAME INDEX idx_873e4a574bd2a4c0 TO report_id');
        $this->addSql('ALTER TABLE prevention_plan RENAME INDEX idx_873e4a5772897d8b TO vulnerability_id');
        $this->addSql('ALTER TABLE prevention_task CHANGE status status ENUM(\'PENDING\', \'COMPLETED\', \'MISSED\') DEFAULT \'PENDING\'');
        $this->addSql('ALTER TABLE prevention_task RENAME INDEX idx_81aca0fc44547a6 TO prevention_plan_id');
        $this->addSql('ALTER TABLE produits DROP FOREIGN KEY FK_BE2DDF8C16880AAF');
        $this->addSql('DROP INDEX IDX_BE2DDF8C16880AAF ON produits');
        $this->addSql('ALTER TABLE produits DROP materiel_id, CHANGE uniteMesure uniteMesure ENUM(\'Kg\', \'L\', \'Piece\') NOT NULL, CHANGE remise remise DOUBLE PRECISION DEFAULT \'0\' NOT NULL');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6905FC057');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6C5568CE4');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6C44547A6');
        $this->addSql('DROP INDEX IDX_794381C6C44547A6 ON review');
        $this->addSql('ALTER TABLE review CHANGE review_type review_type ENUM(\'DIAGNOSIS\', \'PROGRESS\', \'PREVENTION\') NOT NULL, CHANGE status status ENUM(\'PENDING\', \'IN_PROGRESS\', \'COMPLETED\') DEFAULT \'PENDING\', CHANGE ai_analysis ai_analysis TEXT DEFAULT NULL, CHANGE expert_notes expert_notes TEXT DEFAULT NULL, CHANGE expert_verdict expert_verdict ENUM(\'CONTINUE\', \'HEALED\', \'WORSENED\') DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE farmer_response farmer_response ENUM(\'ACCEPTED\', \'REJECTED\', \'ACKNOWLEDGED\') DEFAULT NULL, CHANGE ai_proposed_plan ai_proposed_plan TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT `review_ibfk_2` FOREIGN KEY (treatment_plan_id) REFERENCES treatment_plan (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT `review_ibfk_3` FOREIGN KEY (expert_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE review RENAME INDEX idx_794381c6224cca91 TO diagnostic_id');
        $this->addSql('ALTER TABLE review RENAME INDEX idx_794381c6905fc057 TO treatment_plan_id');
        $this->addSql('ALTER TABLE review RENAME INDEX idx_794381c6c5568ce4 TO expert_id');
        $this->addSql('ALTER TABLE traitement DROP FOREIGN KEY FK_2A356D27224CCA91');
        $this->addSql('DROP INDEX IDX_2A356D27224CCA91 ON traitement');
        $this->addSql('ALTER TABLE traitement CHANGE description_detaillee description_detaillee TEXT DEFAULT NULL, CHANGE type_traitement type_traitement ENUM(\'FONGICIDE\', \'HERBICIDE\', \'INSECTICIDE\', \'BACTERICIDE\', \'NEMATICIDE\', \'VIRUCIDE\', \'NUTRIMENT\', \'REGULATEUR_CROISSANCE\', \'AUTRE\') DEFAULT \'AUTRE\'');
        $this->addSql('ALTER TABLE treatment_plan CHANGE start_date start_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE status status ENUM(\'ACTIVE\', \'COMPLETED\', \'ABANDONED\') DEFAULT \'ACTIVE\'');
        $this->addSql('ALTER TABLE treatment_plan RENAME INDEX idx_1e99976c224cca91 TO diagnostic_id');
        $this->addSql('ALTER TABLE treatment_task CHANGE status status ENUM(\'PENDING\', \'COMPLETED\', \'MISSED\') DEFAULT \'PENDING\', CHANGE tech_x tech_x DOUBLE PRECISION DEFAULT \'0\', CHANGE tech_y tech_y DOUBLE PRECISION DEFAULT \'0\'');
        $this->addSql('ALTER TABLE treatment_task RENAME INDEX idx_91bd1734905fc057 TO treatment_plan_id');
        $this->addSql('ALTER TABLE user CHANGE role role ENUM(\'ADMIN\', \'AGRICULTEUR\', \'CLIENT\', \'AGRONOME\') DEFAULT \'AGRICULTEUR\' NOT NULL, CHANGE points points INT DEFAULT 0, CHANGE level level INT DEFAULT 1, CHANGE two_factor_enabled two_factor_enabled TINYINT DEFAULT 0, CHANGE fingerprint_signature fingerprint_signature MEDIUMTEXT DEFAULT NULL, CHANGE points_fidelite points_fidelite DOUBLE PRECISION DEFAULT \'0\', CHANGE reset_password_code reset_password_code VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE user_badge DROP FOREIGN KEY FK_1C32B345A76ED395');
        $this->addSql('ALTER TABLE user_badge DROP FOREIGN KEY FK_1C32B345F7A2C2FC');
        $this->addSql('ALTER TABLE user_badge CHANGE acquired_at acquired_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT `user_badge_ibfk_1` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT `user_badge_ibfk_2` FOREIGN KEY (badge_id) REFERENCES badge (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE user_badge RENAME INDEX idx_1c32b345f7a2c2fc TO badge_id');
        $this->addSql('ALTER TABLE user_blocks RENAME INDEX idx_abbf8e453ad8644e TO IDX_USER_BLOCKS_SOURCE');
        $this->addSql('ALTER TABLE user_blocks RENAME INDEX idx_abbf8e45233d34c1 TO IDX_USER_BLOCKS_TARGET');
        $this->addSql('ALTER TABLE vulnerability CHANGE type type ENUM(\'PEST_OUTBREAK_RISK\', \'DISEASE_RISK\', \'NUTRIENT_DEFICIENCY\', \'LOW_POLLINATION\', \'SOIL_DEGRADATION\') NOT NULL, CHANGE severity severity ENUM(\'CRITICAL\', \'MEDIUM\', \'LOW\') NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE risk_score risk_score FLOAT DEFAULT NULL, CHANGE estimated_cost_if_occurs estimated_cost_if_occurs FLOAT DEFAULT NULL');
        $this->addSql('ALTER TABLE vulnerability RENAME INDEX idx_6c4e40474bd2a4c0 TO report_id');
    }
}
