<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260404103731 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_badge (acquired_at DATETIME DEFAULT NULL, user_id INT NOT NULL, badge_id INT NOT NULL, INDEX IDX_1C32B345A76ED395 (user_id), INDEX IDX_1C32B345F7A2C2FC (badge_id), PRIMARY KEY (user_id, badge_id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345F7A2C2FC FOREIGN KEY (badge_id) REFERENCES badge (id)');
        $this->addSql('ALTER TABLE ai_recommandation DROP FOREIGN KEY `ai_recommandation_ibfk_1`');
        $this->addSql('ALTER TABLE ai_recommandation DROP FOREIGN KEY `ai_recommandation_ibfk_2`');
        $this->addSql('ALTER TABLE avis DROP FOREIGN KEY `fk_avis_produit`');
        $this->addSql('ALTER TABLE avis DROP FOREIGN KEY `fk_avis_user`');
        $this->addSql('ALTER TABLE chatbot_conversation DROP FOREIGN KEY `chatbot_conversation_ibfk_1`');
        $this->addSql('ALTER TABLE commande DROP FOREIGN KEY `fk_commande_user`');
        $this->addSql('ALTER TABLE coupon_utilisation DROP FOREIGN KEY `fk_couponutilisation_coupon`');
        $this->addSql('ALTER TABLE coupon_utilisation DROP FOREIGN KEY `fk_couponutilisation_user`');
        $this->addSql('ALTER TABLE culture DROP FOREIGN KEY `culture_ibfk_1`');
        $this->addSql('ALTER TABLE detailscommande DROP FOREIGN KEY `fk_details_commande`');
        $this->addSql('ALTER TABLE detailscommande DROP FOREIGN KEY `fk_details_produit`');
        $this->addSql('ALTER TABLE disponibilite_employe DROP FOREIGN KEY `disponibilite_employe_ibfk_1`');
        $this->addSql('ALTER TABLE employe_competence DROP FOREIGN KEY `employe_competence_ibfk_1`');
        $this->addSql('ALTER TABLE employe_competence DROP FOREIGN KEY `employe_competence_ibfk_2`');
        $this->addSql('ALTER TABLE evaluation_performance DROP FOREIGN KEY `evaluation_performance_ibfk_1`');
        $this->addSql('ALTER TABLE evaluation_performance DROP FOREIGN KEY `evaluation_performance_ibfk_2`');
        $this->addSql('ALTER TABLE evenement DROP FOREIGN KEY `evenement_ibfk_1`');
        $this->addSql('ALTER TABLE evenement_favoris DROP FOREIGN KEY `evenement_favoris_ibfk_1`');
        $this->addSql('ALTER TABLE evenement_favoris DROP FOREIGN KEY `evenement_favoris_ibfk_2`');
        $this->addSql('ALTER TABLE maintenance DROP FOREIGN KEY `fk_maintenance_materiel`');
        $this->addSql('ALTER TABLE materiel DROP FOREIGN KEY `fk_materiel_user`');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY `notification_ibfk_1`');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY `notification_ibfk_2`');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY `notification_ibfk_3`');
        $this->addSql('ALTER TABLE notification_config DROP FOREIGN KEY `notification_config_ibfk_1`');
        $this->addSql('ALTER TABLE panier DROP FOREIGN KEY `fk_panier_user`');
        $this->addSql('ALTER TABLE panier_produit DROP FOREIGN KEY `fk_panierproduit_panier`');
        $this->addSql('ALTER TABLE panier_produit DROP FOREIGN KEY `fk_panierproduit_produit`');
        $this->addSql('ALTER TABLE parcelle DROP FOREIGN KEY `parcelle_ibfk_1`');
        $this->addSql('ALTER TABLE participation DROP FOREIGN KEY `participation_ibfk_1`');
        $this->addSql('ALTER TABLE participation DROP FOREIGN KEY `participation_ibfk_2`');
        $this->addSql('ALTER TABLE pointage DROP FOREIGN KEY `pointage_ibfk_1`');
        $this->addSql('ALTER TABLE pointage DROP FOREIGN KEY `pointage_ibfk_2`');
        $this->addSql('ALTER TABLE pointage_photo DROP FOREIGN KEY `pointage_photo_ibfk_1`');
        $this->addSql('ALTER TABLE pointage_photo DROP FOREIGN KEY `pointage_photo_ibfk_2`');
        $this->addSql('ALTER TABLE projet_realise DROP FOREIGN KEY `projet_realise_ibfk_1`');
        $this->addSql('ALTER TABLE reclamation DROP FOREIGN KEY `fk_reclamation_produit`');
        $this->addSql('ALTER TABLE reclamation DROP FOREIGN KEY `fk_reclamation_user`');
        $this->addSql('ALTER TABLE tache_competence_requise DROP FOREIGN KEY `tache_competence_requise_ibfk_1`');
        $this->addSql('ALTER TABLE tache_competence_requise DROP FOREIGN KEY `tache_competence_requise_ibfk_2`');
        $this->addSql('DROP TABLE ai_recommandation');
        $this->addSql('DROP TABLE avis');
        $this->addSql('DROP TABLE chatbot_conversation');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE competence');
        $this->addSql('DROP TABLE coupon');
        $this->addSql('DROP TABLE coupon_utilisation');
        $this->addSql('DROP TABLE culture');
        $this->addSql('DROP TABLE detailscommande');
        $this->addSql('DROP TABLE disponibilite_employe');
        $this->addSql('DROP TABLE employe_competence');
        $this->addSql('DROP TABLE evaluation_performance');
        $this->addSql('DROP TABLE evenement');
        $this->addSql('DROP TABLE evenement_favoris');
        $this->addSql('DROP TABLE maintenance');
        $this->addSql('DROP TABLE materiel');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE notification_config');
        $this->addSql('DROP TABLE panier');
        $this->addSql('DROP TABLE panier_produit');
        $this->addSql('DROP TABLE parcelle');
        $this->addSql('DROP TABLE participation');
        $this->addSql('DROP TABLE pointage');
        $this->addSql('DROP TABLE pointage_photo');
        $this->addSql('DROP TABLE projet_realise');
        $this->addSql('DROP TABLE reclamation');
        $this->addSql('DROP TABLE tache');
        $this->addSql('DROP TABLE tache_competence_requise');
        $this->addSql('ALTER TABLE abonnement CHANGE type type VARCHAR(100) DEFAULT NULL, CHANGE prix prix DOUBLE PRECISION NOT NULL, CHANGE date_debut date_debut DATE DEFAULT NULL, CHANGE date_fin date_fin DATE DEFAULT NULL, CHANGE statut statut VARCHAR(50) DEFAULT \'ACTIF\'');
        $this->addSql('ALTER TABLE abonnement ADD CONSTRAINT FK_351268BBA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE abonnement ADD CONSTRAINT FK_351268BB4CC8505A FOREIGN KEY (offre_id) REFERENCES offre (id)');
        $this->addSql('CREATE INDEX IDX_351268BBA76ED395 ON abonnement (user_id)');
        $this->addSql('CREATE INDEX IDX_351268BB4CC8505A ON abonnement (offre_id)');
        $this->addSql('ALTER TABLE badge CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE icon icon VARCHAR(50) DEFAULT NULL, CHANGE condition_type condition_type ENUM(\'DIAGNOSTIC\',\'POINTS\',\'HEALTHY_PLANTS\',\'SOLUTION\') DEFAULT \'DIAGNOSTIC\'');
        $this->addSql('ALTER TABLE community_comments CHANGE content content LONGTEXT NOT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE community_comments ADD CONSTRAINT FK_ADD8530D4B89032C FOREIGN KEY (post_id) REFERENCES community_posts (id)');
        $this->addSql('ALTER TABLE community_comments ADD CONSTRAINT FK_ADD8530DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE community_comments ADD CONSTRAINT FK_ADD8530DBF2AF943 FOREIGN KEY (parent_comment_id) REFERENCES community_comments (id)');
        $this->addSql('ALTER TABLE community_comments RENAME INDEX post_id TO IDX_ADD8530D4B89032C');
        $this->addSql('ALTER TABLE community_comments RENAME INDEX user_id TO IDX_ADD8530DA76ED395');
        $this->addSql('ALTER TABLE community_comments RENAME INDEX fk_parent_comment TO IDX_ADD8530DBF2AF943');
        $this->addSql('ALTER TABLE community_likes CHANGE vote_type vote_type ENUM(\'LIKE\',\'DISLIKE\') NOT NULL DEFAULT \'LIKE\', CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE community_likes ADD CONSTRAINT FK_32BA3439A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE community_likes ADD CONSTRAINT FK_32BA34394B89032C FOREIGN KEY (post_id) REFERENCES community_posts (id)');
        $this->addSql('ALTER TABLE community_likes ADD CONSTRAINT FK_32BA3439F8697D13 FOREIGN KEY (comment_id) REFERENCES community_comments (id)');
        $this->addSql('CREATE INDEX IDX_32BA3439A76ED395 ON community_likes (user_id)');
        $this->addSql('ALTER TABLE community_likes RENAME INDEX post_id TO IDX_32BA34394B89032C');
        $this->addSql('ALTER TABLE community_likes RENAME INDEX comment_id TO IDX_32BA3439F8697D13');
        $this->addSql('ALTER TABLE community_posts CHANGE description description LONGTEXT DEFAULT NULL, CHANGE image_url image_url VARCHAR(500) DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE community_posts ADD CONSTRAINT FK_F32DC0BEA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE community_posts ADD CONSTRAINT FK_F32DC0BEE50890C4 FOREIGN KEY (solution_comment_id) REFERENCES community_comments (id)');
        $this->addSql('CREATE INDEX IDX_F32DC0BEE50890C4 ON community_posts (solution_comment_id)');
        $this->addSql('ALTER TABLE community_posts RENAME INDEX user_id TO IDX_F32DC0BEA76ED395');
        $this->addSql('ALTER TABLE diagnostic CHANGE date_scan date_scan DATETIME DEFAULT NULL, CHANGE image_scannee image_scannee VARCHAR(255) DEFAULT NULL, CHANGE resultat_ia resultat_ia VARCHAR(255) DEFAULT NULL, CHANGE confiance confiance DOUBLE PRECISION DEFAULT 0, CHANGE latitude latitude DOUBLE PRECISION DEFAULT NULL, CHANGE longitude longitude DOUBLE PRECISION DEFAULT NULL, CHANGE location_label location_label VARCHAR(255) DEFAULT NULL, CHANGE severity severity VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE diagnostic ADD CONSTRAINT FK_FA7C8889A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_FA7C8889A76ED395 ON diagnostic (user_id)');
        $this->addSql('ALTER TABLE employe CHANGE poste poste VARCHAR(100) DEFAULT NULL, CHANGE telephone telephone VARCHAR(20) DEFAULT NULL, CHANGE actif actif TINYINT DEFAULT 1 NOT NULL, CHANGE qr_code_unique qr_code_unique VARCHAR(50) DEFAULT NULL, CHANGE photo_path photo_path VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE employe RENAME INDEX email TO UNIQ_F804D3B9E7927C74');
        $this->addSql('ALTER TABLE employe RENAME INDEX qr_code_unique TO UNIQ_F804D3B9963F987F');
        $this->addSql('ALTER TABLE farm_health_report DROP FOREIGN KEY `farm_health_report_ibfk_1`');
        $this->addSql('ALTER TABLE farm_health_report CHANGE llava_analysis llava_analysis LONGTEXT DEFAULT NULL, CHANGE generated_at generated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE farm_health_report ADD CONSTRAINT FK_5D3720A82827AAD3 FOREIGN KEY (scan_id) REFERENCES farm_health_scan (id)');
        $this->addSql('ALTER TABLE farm_health_report RENAME INDEX scan_id TO IDX_5D3720A82827AAD3');
        $this->addSql('ALTER TABLE farm_health_scan DROP FOREIGN KEY `farm_health_scan_ibfk_1`');
        $this->addSql('ALTER TABLE farm_health_scan CHANGE latitude latitude DOUBLE PRECISION DEFAULT NULL, CHANGE longitude longitude DOUBLE PRECISION DEFAULT NULL, CHANGE concerns concerns LONGTEXT DEFAULT NULL, CHANGE photo_crops photo_crops VARCHAR(500) DEFAULT NULL, CHANGE photo_soil photo_soil VARCHAR(500) DEFAULT NULL, CHANGE photo_edges photo_edges VARCHAR(500) DEFAULT NULL, CHANGE photo_insects photo_insects VARCHAR(500) DEFAULT NULL, CHANGE photo_spacing photo_spacing VARCHAR(500) DEFAULT NULL, CHANGE photo_overview photo_overview VARCHAR(500) DEFAULT NULL, CHANGE scan_date scan_date DATETIME DEFAULT NULL, CHANGE status status ENUM(\'PENDING\',\'PROCESSING\',\'COMPLETED\',\'FAILED\') DEFAULT \'PENDING\'');
        $this->addSql('ALTER TABLE farm_health_scan ADD CONSTRAINT FK_C32EEC75A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE farm_health_scan RENAME INDEX user_id TO IDX_C32EEC75A76ED395');
        $this->addSql('ALTER TABLE offre CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE prix_mensuel prix_mensuel DOUBLE PRECISION NOT NULL, CHANGE avantages avantages LONGTEXT DEFAULT NULL, CHANGE couleur_primaire couleur_primaire VARCHAR(20) DEFAULT \'#6B7F3F\', CHANGE couleur_secondaire couleur_secondaire VARCHAR(20) DEFAULT \'#4A5A2B\', CHANGE date_creation date_creation DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE prevention_plan DROP FOREIGN KEY `prevention_plan_ibfk_1`');
        $this->addSql('ALTER TABLE prevention_plan CHANGE problem_summary problem_summary LONGTEXT DEFAULT NULL, CHANGE steps steps LONGTEXT NOT NULL, CHANGE estimated_cost estimated_cost DOUBLE PRECISION DEFAULT NULL, CHANGE expected_outcome expected_outcome LONGTEXT DEFAULT NULL, CHANGE impact_level impact_level ENUM(\'HIGH\',\'MEDIUM\',\'LOW\'), CHANGE status status ENUM(\'ACTIVE\',\'COMPLETED\',\'ABANDONED\') DEFAULT \'ACTIVE\', CHANGE start_date start_date DATE DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE prevention_plan ADD CONSTRAINT FK_873E4A574BD2A4C0 FOREIGN KEY (report_id) REFERENCES farm_health_report (id)');
        $this->addSql('ALTER TABLE prevention_plan RENAME INDEX report_id TO IDX_873E4A574BD2A4C0');
        $this->addSql('ALTER TABLE prevention_plan RENAME INDEX vulnerability_id TO IDX_873E4A5772897D8B');
        $this->addSql('ALTER TABLE prevention_task DROP FOREIGN KEY `prevention_task_ibfk_1`');
        $this->addSql('ALTER TABLE prevention_task CHANGE status status ENUM(\'PENDING\',\'COMPLETED\',\'MISSED\') DEFAULT \'PENDING\', CHANGE proof_photo_url proof_photo_url VARCHAR(500) DEFAULT NULL, CHANGE completed_at completed_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE prevention_task ADD CONSTRAINT FK_81ACA0FC44547A6 FOREIGN KEY (prevention_plan_id) REFERENCES prevention_plan (id)');
        $this->addSql('ALTER TABLE prevention_task RENAME INDEX prevention_plan_id TO IDX_81ACA0FC44547A6');
        $this->addSql('ALTER TABLE produits DROP FOREIGN KEY `fk_produit_user`');
        $this->addSql('DROP INDEX idx_produit_categorie ON produits');
        $this->addSql('ALTER TABLE produits ADD remise DOUBLE PRECISION DEFAULT 0 NOT NULL, ADD typeRemise VARCHAR(20) DEFAULT NULL, DROP device, CHANGE nom nom VARCHAR(100) NOT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE prix prix DOUBLE PRECISION NOT NULL, CHANGE quantiteStock quantiteStock INT NOT NULL, CHANGE categorie categorie VARCHAR(100) DEFAULT NULL, CHANGE uniteMesure uniteMesure ENUM(\'Kg\',\'L\',\'Piece\') NOT NULL, CHANGE image image VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE produits ADD CONSTRAINT FK_BE2DDF8CFE6E88D7 FOREIGN KEY (idUser) REFERENCES user (id)');
        $this->addSql('ALTER TABLE produits RENAME INDEX idx_produit_iduser TO IDX_BE2DDF8CFE6E88D7');
        $this->addSql('ALTER TABLE review CHANGE diagnostic_id diagnostic_id INT NOT NULL, CHANGE review_type review_type ENUM(\'DIAGNOSIS\',\'PROGRESS\',\'PREVENTION\') NOT NULL, CHANGE status status ENUM(\'PENDING\',\'IN_PROGRESS\',\'COMPLETED\') DEFAULT \'PENDING\', CHANGE photo_url photo_url VARCHAR(500) DEFAULT NULL, CHANGE ai_analysis ai_analysis LONGTEXT DEFAULT NULL, CHANGE ai_proposed_plan ai_proposed_plan LONGTEXT DEFAULT NULL, CHANGE expert_notes expert_notes LONGTEXT DEFAULT NULL, CHANGE expert_verdict expert_verdict ENUM(\'CONTINUE\',\'HEALED\',\'WORSENED\'), CHANGE expert_disease_name expert_disease_name VARCHAR(255) DEFAULT NULL, CHANGE farmer_response farmer_response ENUM(\'ACCEPTED\',\'REJECTED\',\'ACKNOWLEDGED\'), CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6224CCA91 FOREIGN KEY (diagnostic_id) REFERENCES diagnostic (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6905FC057 FOREIGN KEY (treatment_plan_id) REFERENCES treatment_plan (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6C5568CE4 FOREIGN KEY (expert_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6C44547A6 FOREIGN KEY (prevention_plan_id) REFERENCES prevention_plan (id)');
        $this->addSql('CREATE INDEX IDX_794381C6224CCA91 ON review (diagnostic_id)');
        $this->addSql('CREATE INDEX IDX_794381C6905FC057 ON review (treatment_plan_id)');
        $this->addSql('CREATE INDEX IDX_794381C6C5568CE4 ON review (expert_id)');
        $this->addSql('CREATE INDEX IDX_794381C6C44547A6 ON review (prevention_plan_id)');
        $this->addSql('ALTER TABLE traitement CHANGE description_detaillee description_detaillee LONGTEXT DEFAULT NULL, CHANGE type_traitement type_traitement ENUM(\'FONGICIDE\',\'HERBICIDE\',\'INSECTICIDE\',\'BACTERICIDE\',\'NEMATICIDE\',\'VIRUCIDE\',\'NUTRIMENT\',\'REGULATEUR_CROISSANCE\',\'AUTRE\') DEFAULT \'AUTRE\', CHANGE duree_recommandee duree_recommandee VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE traitement ADD CONSTRAINT FK_2A356D27224CCA91 FOREIGN KEY (diagnostic_id) REFERENCES diagnostic (id)');
        $this->addSql('CREATE INDEX IDX_2A356D27224CCA91 ON traitement (diagnostic_id)');
        $this->addSql('ALTER TABLE treatment_plan DROP expert_advice, DROP is_expert_verified, DROP follow_up_image_url, DROP review_type, CHANGE start_date start_date DATETIME DEFAULT NULL, CHANGE status status ENUM(\'ACTIVE\',\'COMPLETED\',\'ABANDONED\') DEFAULT \'ACTIVE\'');
        $this->addSql('ALTER TABLE treatment_plan ADD CONSTRAINT FK_1E99976C224CCA91 FOREIGN KEY (diagnostic_id) REFERENCES diagnostic (id)');
        $this->addSql('ALTER TABLE treatment_plan RENAME INDEX diagnostic_id TO IDX_1E99976C224CCA91');
        $this->addSql('ALTER TABLE treatment_task DROP image_path, CHANGE status status ENUM(\'PENDING\',\'COMPLETED\',\'MISSED\') DEFAULT \'PENDING\', CHANGE tech_x tech_x DOUBLE PRECISION DEFAULT NULL, CHANGE tech_y tech_y DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE treatment_task ADD CONSTRAINT FK_91BD1734905FC057 FOREIGN KEY (treatment_plan_id) REFERENCES treatment_plan (id)');
        $this->addSql('ALTER TABLE treatment_task RENAME INDEX treatment_plan_id TO IDX_91BD1734905FC057');
        $this->addSql('ALTER TABLE user ADD points_fidelite DOUBLE PRECISION DEFAULT 0 NOT NULL, DROP biometric_enabled, CHANGE role role ENUM(\'ADMIN\',\'AGRICULTEUR\',\'CLIENT\',\'AGRONOME\') NOT NULL DEFAULT \'AGRICULTEUR\', CHANGE points points INT DEFAULT 0 NOT NULL, CHANGE level level INT DEFAULT 1 NOT NULL, CHANGE two_factor_enabled two_factor_enabled TINYINT DEFAULT 0 NOT NULL, CHANGE two_factor_code two_factor_code VARCHAR(10) DEFAULT NULL, CHANGE two_factor_expires_at two_factor_expires_at DATETIME DEFAULT NULL, CHANGE fingerprint_signature fingerprint_signature LONGTEXT DEFAULT NULL, CHANGE reset_password_code reset_password_code VARCHAR(10) DEFAULT NULL, CHANGE reset_password_expires_at reset_password_expires_at DATETIME DEFAULT NULL, CHANGE phone phone VARCHAR(20) DEFAULT NULL, CHANGE location location VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE vulnerability DROP FOREIGN KEY `vulnerability_ibfk_1`');
        $this->addSql('ALTER TABLE vulnerability CHANGE type type ENUM(\'PEST_OUTBREAK_RISK\',\'DISEASE_RISK\',\'NUTRIENT_DEFICIENCY\',\'LOW_POLLINATION\',\'SOIL_DEGRADATION\') NOT NULL, CHANGE severity severity ENUM(\'CRITICAL\',\'MEDIUM\',\'LOW\') NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE risk_score risk_score DOUBLE PRECISION DEFAULT NULL, CHANGE estimated_cost_if_occurs estimated_cost_if_occurs DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE vulnerability ADD CONSTRAINT FK_6C4E40474BD2A4C0 FOREIGN KEY (report_id) REFERENCES farm_health_report (id)');
        $this->addSql('ALTER TABLE vulnerability RENAME INDEX report_id TO IDX_6C4E40474BD2A4C0');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ai_recommandation (id_recommandation INT AUTO_INCREMENT NOT NULL, id_tache INT NOT NULL, id_employe_recommande INT NOT NULL, score_matching NUMERIC(5, 2) DEFAULT \'NULL\', score_competences NUMERIC(5, 2) DEFAULT \'NULL\', score_experience NUMERIC(5, 2) DEFAULT \'NULL\', score_performance NUMERIC(5, 2) DEFAULT \'NULL\', score_disponibilite NUMERIC(5, 2) DEFAULT \'NULL\', rang_recommandation INT DEFAULT NULL, raison_recommandation TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, acceptee TINYINT DEFAULT 0, date_recommandation DATETIME DEFAULT \'current_timestamp()\', INDEX idx_tache (id_tache), INDEX idx_score (score_matching), INDEX idx_acceptee (acceptee), INDEX id_employe_recommande (id_employe_recommande), PRIMARY KEY (id_recommandation)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE avis (idAvis INT AUTO_INCREMENT NOT NULL, idUser INT NOT NULL, idProduit INT NOT NULL, note INT NOT NULL, commentaire TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, dateAvis DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_avis_idProduit (idProduit), INDEX idx_avis_idUser (idUser), PRIMARY KEY (idAvis)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE chatbot_conversation (id_conversation INT AUTO_INCREMENT NOT NULL, id_utilisateur INT NOT NULL, message_utilisateur TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, reponse_chatbot TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, intention VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, contexte LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, satisfaction INT DEFAULT NULL, date_message DATETIME DEFAULT \'current_timestamp()\', INDEX idx_date (date_message), INDEX idx_utilisateur (id_utilisateur), INDEX idx_intention (intention), PRIMARY KEY (id_conversation)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE commande (idCommande INT AUTO_INCREMENT NOT NULL, date_commande DATE NOT NULL, etat VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'en_cours\'\'\' NOT NULL COLLATE `utf8mb4_general_ci`, total FLOAT DEFAULT \'0\' NOT NULL, idUser INT NOT NULL, frais_livraison FLOAT DEFAULT \'0\', mode_livraison ENUM(\'RECUPERATION\', \'LIVRAISON\') CHARACTER SET utf8mb4 DEFAULT \'\'\'RECUPERATION\'\'\' COLLATE `utf8mb4_general_ci`, payee_par_points TINYINT DEFAULT 0, INDEX idx_commande_idUser (idUser), PRIMARY KEY (idCommande)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE competence (id_competence INT AUTO_INCREMENT NOT NULL, nom VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, categorie VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, date_creation DATETIME DEFAULT \'current_timestamp()\', UNIQUE INDEX nom (nom), INDEX idx_categorie (categorie), PRIMARY KEY (id_competence)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE coupon (idCoupon INT AUTO_INCREMENT NOT NULL, code VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, typeReduction ENUM(\'POURCENTAGE\', \'FIXE\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, valeur DOUBLE PRECISION NOT NULL, dateDebut DATE NOT NULL, dateFin DATE NOT NULL, utilisationMax INT DEFAULT 0 NOT NULL, utilisationActuelle INT DEFAULT 0 NOT NULL, actif TINYINT DEFAULT 1 NOT NULL, montantMin DOUBLE PRECISION DEFAULT \'0\' NOT NULL, limiteParUser INT DEFAULT 1 NOT NULL, INDEX idx_coupon_code (code), UNIQUE INDEX code (code), INDEX idx_coupon_actif (actif), PRIMARY KEY (idCoupon)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE coupon_utilisation (id INT AUTO_INCREMENT NOT NULL, idCoupon INT NOT NULL, idUser INT NOT NULL, nombreUtilisation INT DEFAULT 0 NOT NULL, INDEX fk_couponutilisation_user (idUser), UNIQUE INDEX unique_coupon_user (idCoupon, idUser), INDEX IDX_C74CAFE47AE9798 (idCoupon), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE culture (id INT AUTO_INCREMENT NOT NULL, nom_culture VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, type_culture VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, saison VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, date_plantation DATE DEFAULT \'NULL\', date_recolte_prevue DATE DEFAULT \'NULL\', etat_culture VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'en_croissance\'\'\' COLLATE `utf8mb4_general_ci`, parcelle_id INT NOT NULL, surface_utilisee DOUBLE PRECISION DEFAULT \'0\' NOT NULL, rendement_estime DOUBLE PRECISION DEFAULT \'0\', INDEX fk_culture_parcelle (parcelle_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE detailscommande (idDetails INT AUTO_INCREMENT NOT NULL, idCommande INT NOT NULL, idProduit INT NOT NULL, quantite INT DEFAULT 1 NOT NULL, prix_unitaire FLOAT NOT NULL, INDEX idx_details_idCommande (idCommande), INDEX idx_details_idProduit (idProduit), PRIMARY KEY (idDetails)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE disponibilite_employe (id INT AUTO_INCREMENT NOT NULL, id_employe INT NOT NULL, date_debut DATE NOT NULL, date_fin DATE NOT NULL, charge_travail INT DEFAULT 0, taches_en_cours INT DEFAULT 0, statut VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'Disponible\'\'\' COLLATE `utf8mb4_general_ci`, notes TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, date_maj DATETIME DEFAULT \'current_timestamp()\', INDEX idx_dates (date_debut, date_fin), INDEX idx_statut (statut), INDEX idx_employe (id_employe), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE employe_competence (id INT AUTO_INCREMENT NOT NULL, id_employe INT NOT NULL, id_competence INT NOT NULL, niveau INT DEFAULT 1 NOT NULL, annees_experience NUMERIC(3, 1) DEFAULT \'0.0\', derniere_utilisation DATE DEFAULT \'NULL\', certification VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, notes TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, date_ajout DATETIME DEFAULT \'current_timestamp()\', date_modification DATETIME DEFAULT \'current_timestamp()\', INDEX idx_niveau (niveau), UNIQUE INDEX unique_employe_competence (id_employe, id_competence), INDEX idx_experience (annees_experience), INDEX id_competence (id_competence), INDEX IDX_161DB2B826997AC9 (id_employe), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE evaluation_performance (id_evaluation INT AUTO_INCREMENT NOT NULL, id_employe INT NOT NULL, id_tache INT DEFAULT NULL, note_qualite INT DEFAULT NULL, note_rapidite INT DEFAULT NULL, note_autonomie INT DEFAULT NULL, note_communication INT DEFAULT NULL, note_globale NUMERIC(3, 2) DEFAULT \'NULL\', commentaire TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, evaluateur VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, date_evaluation DATETIME DEFAULT \'current_timestamp()\', INDEX id_tache (id_tache), INDEX idx_employe (id_employe), INDEX idx_note (note_globale), PRIMARY KEY (id_evaluation)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE evenement (id INT AUTO_INCREMENT NOT NULL, titre VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, lieu VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, date_debut DATE NOT NULL, date_fin DATE NOT NULL, type VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, nombre_places_max INT DEFAULT 50 NOT NULL, organisateur VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, image_url VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, statut VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'A_VENIR\'\'\' NOT NULL COLLATE `utf8mb4_general_ci`, date_creation DATETIME DEFAULT \'current_timestamp()\', id_createur INT NOT NULL, INDEX idx_evenement_statut (statut), INDEX idx_evenement_createur (id_createur), INDEX idx_evenement_date_debut (date_debut), INDEX idx_evenement_type (type), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE evenement_favoris (id INT AUTO_INCREMENT NOT NULL, id_evenement INT NOT NULL, id_utilisateur INT NOT NULL, date_ajout DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_favoris_user (id_utilisateur), INDEX idx_favoris_event (id_evenement), UNIQUE INDEX unique_favori (id_evenement, id_utilisateur), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE maintenance (id_maintenance INT AUTO_INCREMENT NOT NULL, materiel_id INT NOT NULL, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, date_maintenance DATE NOT NULL, cout NUMERIC(10, 2) NOT NULL, google_calendar_event_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, statut_maintenance VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'planifiee\'\'\' COLLATE `utf8mb4_general_ci`, date_planifiee DATE DEFAULT \'NULL\', date_realisee DATE DEFAULT \'NULL\', type_maintenance VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'preventive\'\'\' COLLATE `utf8mb4_general_ci`, INDEX idx_statut (statut_maintenance), INDEX idx_date_planifiee (date_planifiee), INDEX idx_materiel_id (materiel_id), PRIMARY KEY (id_maintenance)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE materiel (id_materiel INT AUTO_INCREMENT NOT NULL, nom VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, type VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, etat VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, user_id INT NOT NULL, date_achat DATE DEFAULT \'NULL\', date_prochaine_maintenance DATE DEFAULT \'NULL\', google_calendar_event_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, derniere_maintenance DATE DEFAULT \'NULL\', frequence_maintenance_mois INT DEFAULT 12, INDEX fk_materiel_user (user_id), INDEX idx_materiel_user (user_id), PRIMARY KEY (id_materiel)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE notification (id_notification INT AUTO_INCREMENT NOT NULL, type VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, priorite VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, titre VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, message TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, id_agriculteur INT NOT NULL, id_tache INT DEFAULT NULL, id_employe INT DEFAULT NULL, lue TINYINT DEFAULT 0, archivee TINYINT DEFAULT 0, date_creation DATETIME DEFAULT \'current_timestamp()\', date_lecture DATETIME DEFAULT \'NULL\', INDEX idx_lue (lue), INDEX id_employe (id_employe), INDEX idx_date (date_creation), INDEX idx_agriculteur (id_agriculteur), INDEX idx_type (type), INDEX id_tache (id_tache), PRIMARY KEY (id_notification)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE notification_config (id_config INT AUTO_INCREMENT NOT NULL, id_agriculteur INT NOT NULL, seuil_taches_employe INT DEFAULT 10, seuil_jours_inactivite INT DEFAULT 30, activer_notifications TINYINT DEFAULT 1, activer_sons TINYINT DEFAULT 1, UNIQUE INDEX id_agriculteur (id_agriculteur), PRIMARY KEY (id_config)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE panier (idPanier INT AUTO_INCREMENT NOT NULL, dateCreation DATE NOT NULL, totalMontant FLOAT DEFAULT \'0\' NOT NULL, totalProduits INT DEFAULT 0 NOT NULL, idUser INT NOT NULL, INDEX idx_panier_idUser (idUser), PRIMARY KEY (idPanier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE panier_produit (idPanier INT NOT NULL, idProduit INT NOT NULL, quantite INT DEFAULT 1 NOT NULL, INDEX fk_panierproduit_produit (idProduit), INDEX IDX_D31F28A647DDA568 (idPanier), PRIMARY KEY (idPanier, idProduit)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE parcelle (id INT AUTO_INCREMENT NOT NULL, surface DOUBLE PRECISION NOT NULL, localisation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, type_sol VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, systeme_irrigation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, statut VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'active\'\'\' COLLATE `utf8mb4_general_ci`, agriculteur_id INT DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT \'NULL\', longitude DOUBLE PRECISION DEFAULT \'NULL\', INDEX fk_parcelle_agriculteur (agriculteur_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE participation (id INT AUTO_INCREMENT NOT NULL, id_evenement INT NOT NULL, id_utilisateur INT NOT NULL, date_inscription DATETIME DEFAULT \'current_timestamp()\', statut VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'CONFIRME\'\'\' NOT NULL COLLATE `utf8mb4_general_ci`, commentaire TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, nombre_personnes INT DEFAULT 1, note INT DEFAULT 0, avis TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, attestation_envoyee TINYINT DEFAULT 0, qr_code_token VARCHAR(64) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, INDEX idx_participation_evenement (id_evenement), UNIQUE INDEX unique_participation (id_evenement, id_utilisateur), INDEX idx_participation_utilisateur (id_utilisateur), INDEX idx_participation_statut (statut), UNIQUE INDEX unique_qr_token (qr_code_token), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pointage (id_pointage INT AUTO_INCREMENT NOT NULL, id_employe INT NOT NULL, id_agriculteur INT DEFAULT NULL, date_pointage DATE DEFAULT \'curdate()\' NOT NULL, heure_arrivee TIME DEFAULT \'NULL\', heure_depart TIME DEFAULT \'NULL\', statut ENUM(\'Present\', \'Retard\', \'Absent\', \'Depart\') CHARACTER SET utf8mb4 DEFAULT \'\'\'Present\'\'\' COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, INDEX idx_pointage_date (date_pointage), INDEX idx_pointage_employe (id_employe), UNIQUE INDEX unique_pointage_jour (id_employe, date_pointage), INDEX idx_pointage_agri (id_agriculteur), PRIMARY KEY (id_pointage)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pointage_photo (id INT AUTO_INCREMENT NOT NULL, id_pointage INT NOT NULL, id_employe INT NOT NULL, photo_path VARCHAR(500) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'Chemin absolu : ~/Ardhi/pointage_photos/POINT_5_20260221_083000.jpg\', date_prise DATETIME DEFAULT \'current_timestamp()\' NOT NULL, type_pointage ENUM(\'ARRIVEE\', \'DEPART\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, INDEX idx_pp_pointage (id_pointage), INDEX idx_pp_employe (id_employe), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE projet_realise (id_projet INT AUTO_INCREMENT NOT NULL, id_employe INT NOT NULL, titre VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, date_debut DATE DEFAULT \'NULL\', date_fin DATE DEFAULT \'NULL\', statut VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'Terminé\'\'\' COLLATE `utf8mb4_general_ci`, resultat TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, taux_reussite INT DEFAULT NULL, technologies_utilisees TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, lien_reference VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, date_creation DATETIME DEFAULT \'current_timestamp()\', INDEX idx_statut (statut), INDEX idx_employe (id_employe), PRIMARY KEY (id_projet)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE reclamation (idReclamation INT AUTO_INCREMENT NOT NULL, description TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, type ENUM(\'QUALITE_RECOLTE\', \'PRODUIT_AVARIE\', \'QUANTITE_INCORRECTE\', \'PRIX_NON_CONFORME\', \'PRODUIT_NON_CONFORME\', \'RETARD_LIVRAISON\', \'AUTRE\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, statut ENUM(\'EN_ATTENTE\', \'EN_COURS\', \'RESOLUE\', \'REJETEE\') CHARACTER SET utf8mb4 DEFAULT \'\'\'EN_ATTENTE\'\'\' NOT NULL COLLATE `utf8mb4_general_ci`, dateReclamation DATETIME DEFAULT \'current_timestamp()\' NOT NULL, nomProduit VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_general_ci`, idProduit INT NOT NULL, idUser INT NOT NULL, INDEX idx_reclamation_idUser (idUser), INDEX idx_reclamation_idProduit (idProduit), PRIMARY KEY (idReclamation)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE tache (id_tache INT AUTO_INCREMENT NOT NULL, titre VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, statut VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'En attente\'\'\' COLLATE `utf8mb4_unicode_ci`, date_debut DATE DEFAULT \'NULL\', date_fin DATE DEFAULT \'NULL\', id_employe INT DEFAULT NULL, id_agriculteur INT DEFAULT NULL, priorite INT DEFAULT NULL COMMENT \'1=Basse, 2=Moyenne, 3=Haute, 4=Critique\', categorie VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'Plantation, Récolte, Irrigation, etc.\', date_modification DATETIME DEFAULT \'current_timestamp()\' NOT NULL, google_event_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, type_tache VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\'\'AUTRE\'\'\' COLLATE `utf8mb4_unicode_ci`, google_calendar_event_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY (id_tache)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE tache_competence_requise (id INT AUTO_INCREMENT NOT NULL, id_tache INT NOT NULL, id_competence INT NOT NULL, niveau_requis INT DEFAULT 2 NOT NULL, importance INT DEFAULT 5, date_ajout DATETIME DEFAULT \'current_timestamp()\', INDEX idx_niveau (niveau_requis), UNIQUE INDEX unique_tache_competence (id_tache, id_competence), INDEX idx_importance (importance), INDEX id_competence (id_competence), INDEX IDX_FEBDEA6A7D026145 (id_tache), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE ai_recommandation ADD CONSTRAINT `ai_recommandation_ibfk_1` FOREIGN KEY (id_tache) REFERENCES tache (id_tache) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ai_recommandation ADD CONSTRAINT `ai_recommandation_ibfk_2` FOREIGN KEY (id_employe_recommande) REFERENCES employe (id_employe) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT `fk_avis_produit` FOREIGN KEY (idProduit) REFERENCES produits (idProduit) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT `fk_avis_user` FOREIGN KEY (idUser) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chatbot_conversation ADD CONSTRAINT `chatbot_conversation_ibfk_1` FOREIGN KEY (id_utilisateur) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT `fk_commande_user` FOREIGN KEY (idUser) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE coupon_utilisation ADD CONSTRAINT `fk_couponutilisation_coupon` FOREIGN KEY (idCoupon) REFERENCES coupon (idCoupon) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE coupon_utilisation ADD CONSTRAINT `fk_couponutilisation_user` FOREIGN KEY (idUser) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE culture ADD CONSTRAINT `culture_ibfk_1` FOREIGN KEY (parcelle_id) REFERENCES parcelle (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE detailscommande ADD CONSTRAINT `fk_details_commande` FOREIGN KEY (idCommande) REFERENCES commande (idCommande) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE detailscommande ADD CONSTRAINT `fk_details_produit` FOREIGN KEY (idProduit) REFERENCES produits (idProduit) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE disponibilite_employe ADD CONSTRAINT `disponibilite_employe_ibfk_1` FOREIGN KEY (id_employe) REFERENCES employe (id_employe) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employe_competence ADD CONSTRAINT `employe_competence_ibfk_1` FOREIGN KEY (id_employe) REFERENCES employe (id_employe) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employe_competence ADD CONSTRAINT `employe_competence_ibfk_2` FOREIGN KEY (id_competence) REFERENCES competence (id_competence) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluation_performance ADD CONSTRAINT `evaluation_performance_ibfk_1` FOREIGN KEY (id_employe) REFERENCES employe (id_employe) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluation_performance ADD CONSTRAINT `evaluation_performance_ibfk_2` FOREIGN KEY (id_tache) REFERENCES tache (id_tache) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE evenement ADD CONSTRAINT `evenement_ibfk_1` FOREIGN KEY (id_createur) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evenement_favoris ADD CONSTRAINT `evenement_favoris_ibfk_1` FOREIGN KEY (id_evenement) REFERENCES evenement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evenement_favoris ADD CONSTRAINT `evenement_favoris_ibfk_2` FOREIGN KEY (id_utilisateur) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE maintenance ADD CONSTRAINT `fk_maintenance_materiel` FOREIGN KEY (materiel_id) REFERENCES materiel (id_materiel) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE materiel ADD CONSTRAINT `fk_materiel_user` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT `notification_ibfk_1` FOREIGN KEY (id_agriculteur) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT `notification_ibfk_2` FOREIGN KEY (id_tache) REFERENCES tache (id_tache) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT `notification_ibfk_3` FOREIGN KEY (id_employe) REFERENCES employe (id_employe) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification_config ADD CONSTRAINT `notification_config_ibfk_1` FOREIGN KEY (id_agriculteur) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE panier ADD CONSTRAINT `fk_panier_user` FOREIGN KEY (idUser) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE panier_produit ADD CONSTRAINT `fk_panierproduit_panier` FOREIGN KEY (idPanier) REFERENCES panier (idPanier) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE panier_produit ADD CONSTRAINT `fk_panierproduit_produit` FOREIGN KEY (idProduit) REFERENCES produits (idProduit) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE parcelle ADD CONSTRAINT `parcelle_ibfk_1` FOREIGN KEY (agriculteur_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT `participation_ibfk_1` FOREIGN KEY (id_evenement) REFERENCES evenement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT `participation_ibfk_2` FOREIGN KEY (id_utilisateur) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pointage ADD CONSTRAINT `pointage_ibfk_1` FOREIGN KEY (id_employe) REFERENCES employe (id_employe) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pointage ADD CONSTRAINT `pointage_ibfk_2` FOREIGN KEY (id_agriculteur) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE pointage_photo ADD CONSTRAINT `pointage_photo_ibfk_1` FOREIGN KEY (id_pointage) REFERENCES pointage (id_pointage) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pointage_photo ADD CONSTRAINT `pointage_photo_ibfk_2` FOREIGN KEY (id_employe) REFERENCES employe (id_employe) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE projet_realise ADD CONSTRAINT `projet_realise_ibfk_1` FOREIGN KEY (id_employe) REFERENCES employe (id_employe) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT `fk_reclamation_produit` FOREIGN KEY (idProduit) REFERENCES produits (idProduit) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT `fk_reclamation_user` FOREIGN KEY (idUser) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tache_competence_requise ADD CONSTRAINT `tache_competence_requise_ibfk_1` FOREIGN KEY (id_tache) REFERENCES tache (id_tache) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tache_competence_requise ADD CONSTRAINT `tache_competence_requise_ibfk_2` FOREIGN KEY (id_competence) REFERENCES competence (id_competence) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_badge DROP FOREIGN KEY FK_1C32B345A76ED395');
        $this->addSql('ALTER TABLE user_badge DROP FOREIGN KEY FK_1C32B345F7A2C2FC');
        $this->addSql('DROP TABLE user_badge');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE abonnement DROP FOREIGN KEY FK_351268BBA76ED395');
        $this->addSql('ALTER TABLE abonnement DROP FOREIGN KEY FK_351268BB4CC8505A');
        $this->addSql('DROP INDEX IDX_351268BBA76ED395 ON abonnement');
        $this->addSql('DROP INDEX IDX_351268BB4CC8505A ON abonnement');
        $this->addSql('ALTER TABLE abonnement CHANGE type type VARCHAR(100) DEFAULT \'NULL\', CHANGE prix prix FLOAT NOT NULL, CHANGE date_debut date_debut DATE DEFAULT \'NULL\', CHANGE date_fin date_fin DATE DEFAULT \'NULL\', CHANGE statut statut VARCHAR(50) DEFAULT \'\'\'ACTIF\'\'\'');
        $this->addSql('ALTER TABLE badge CHANGE description description VARCHAR(255) DEFAULT \'NULL\', CHANGE icon icon VARCHAR(50) DEFAULT \'NULL\', CHANGE condition_type condition_type ENUM(\'DIAGNOSTIC\', \'POINTS\', \'HEALTHY_PLANTS\', \'SOLUTION\') DEFAULT \'\'\'DIAGNOSTIC\'\'\'');
        $this->addSql('ALTER TABLE community_comments DROP FOREIGN KEY FK_ADD8530D4B89032C');
        $this->addSql('ALTER TABLE community_comments DROP FOREIGN KEY FK_ADD8530DA76ED395');
        $this->addSql('ALTER TABLE community_comments DROP FOREIGN KEY FK_ADD8530DBF2AF943');
        $this->addSql('ALTER TABLE community_comments CHANGE content content TEXT NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'current_timestamp()\'');
        $this->addSql('ALTER TABLE community_comments RENAME INDEX idx_add8530dbf2af943 TO fk_parent_comment');
        $this->addSql('ALTER TABLE community_comments RENAME INDEX idx_add8530d4b89032c TO post_id');
        $this->addSql('ALTER TABLE community_comments RENAME INDEX idx_add8530da76ed395 TO user_id');
        $this->addSql('ALTER TABLE community_likes DROP FOREIGN KEY FK_32BA3439A76ED395');
        $this->addSql('ALTER TABLE community_likes DROP FOREIGN KEY FK_32BA34394B89032C');
        $this->addSql('ALTER TABLE community_likes DROP FOREIGN KEY FK_32BA3439F8697D13');
        $this->addSql('DROP INDEX IDX_32BA3439A76ED395 ON community_likes');
        $this->addSql('ALTER TABLE community_likes CHANGE vote_type vote_type ENUM(\'LIKE\', \'DISLIKE\') DEFAULT \'\'\'LIKE\'\'\' NOT NULL, CHANGE created_at created_at DATETIME DEFAULT \'current_timestamp()\'');
        $this->addSql('ALTER TABLE community_likes RENAME INDEX idx_32ba3439f8697d13 TO comment_id');
        $this->addSql('ALTER TABLE community_likes RENAME INDEX idx_32ba34394b89032c TO post_id');
        $this->addSql('ALTER TABLE community_posts DROP FOREIGN KEY FK_F32DC0BEA76ED395');
        $this->addSql('ALTER TABLE community_posts DROP FOREIGN KEY FK_F32DC0BEE50890C4');
        $this->addSql('DROP INDEX IDX_F32DC0BEE50890C4 ON community_posts');
        $this->addSql('ALTER TABLE community_posts CHANGE description description TEXT DEFAULT NULL, CHANGE image_url image_url VARCHAR(500) DEFAULT \'NULL\', CHANGE created_at created_at DATETIME DEFAULT \'current_timestamp()\'');
        $this->addSql('ALTER TABLE community_posts RENAME INDEX idx_f32dc0bea76ed395 TO user_id');
        $this->addSql('ALTER TABLE diagnostic DROP FOREIGN KEY FK_FA7C8889A76ED395');
        $this->addSql('DROP INDEX IDX_FA7C8889A76ED395 ON diagnostic');
        $this->addSql('ALTER TABLE diagnostic CHANGE date_scan date_scan DATETIME DEFAULT \'current_timestamp()\', CHANGE image_scannee image_scannee VARCHAR(500) DEFAULT \'NULL\', CHANGE resultat_ia resultat_ia TEXT DEFAULT NULL, CHANGE confiance confiance FLOAT DEFAULT \'0\', CHANGE latitude latitude DOUBLE PRECISION DEFAULT \'NULL\', CHANGE longitude longitude DOUBLE PRECISION DEFAULT \'NULL\', CHANGE location_label location_label VARCHAR(255) DEFAULT \'NULL\', CHANGE severity severity VARCHAR(20) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE employe CHANGE poste poste VARCHAR(100) DEFAULT \'NULL\', CHANGE telephone telephone VARCHAR(20) DEFAULT \'NULL\', CHANGE actif actif TINYINT DEFAULT 1, CHANGE qr_code_unique qr_code_unique VARCHAR(50) DEFAULT \'NULL\', CHANGE photo_path photo_path VARCHAR(500) DEFAULT \'NULL\' COMMENT \'Chemin absolu vers la photo de profil : ~/Ardhi/photos_employes/EMP_42.jpg\'');
        $this->addSql('ALTER TABLE employe RENAME INDEX uniq_f804d3b9e7927c74 TO email');
        $this->addSql('ALTER TABLE employe RENAME INDEX uniq_f804d3b9963f987f TO qr_code_unique');
        $this->addSql('ALTER TABLE farm_health_report DROP FOREIGN KEY FK_5D3720A82827AAD3');
        $this->addSql('ALTER TABLE farm_health_report CHANGE llava_analysis llava_analysis TEXT DEFAULT NULL, CHANGE generated_at generated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL');
        $this->addSql('ALTER TABLE farm_health_report ADD CONSTRAINT `farm_health_report_ibfk_1` FOREIGN KEY (scan_id) REFERENCES farm_health_scan (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE farm_health_report RENAME INDEX idx_5d3720a82827aad3 TO scan_id');
        $this->addSql('ALTER TABLE farm_health_scan DROP FOREIGN KEY FK_C32EEC75A76ED395');
        $this->addSql('ALTER TABLE farm_health_scan CHANGE latitude latitude DOUBLE PRECISION DEFAULT \'NULL\', CHANGE longitude longitude DOUBLE PRECISION DEFAULT \'NULL\', CHANGE concerns concerns TEXT DEFAULT NULL, CHANGE photo_crops photo_crops VARCHAR(500) DEFAULT \'NULL\', CHANGE photo_soil photo_soil VARCHAR(500) DEFAULT \'NULL\', CHANGE photo_edges photo_edges VARCHAR(500) DEFAULT \'NULL\', CHANGE photo_insects photo_insects VARCHAR(500) DEFAULT \'NULL\', CHANGE photo_spacing photo_spacing VARCHAR(500) DEFAULT \'NULL\', CHANGE photo_overview photo_overview VARCHAR(500) DEFAULT \'NULL\', CHANGE scan_date scan_date DATETIME DEFAULT \'current_timestamp()\' NOT NULL, CHANGE status status ENUM(\'PENDING\', \'PROCESSING\', \'COMPLETED\', \'FAILED\') DEFAULT \'\'\'PENDING\'\'\'');
        $this->addSql('ALTER TABLE farm_health_scan ADD CONSTRAINT `farm_health_scan_ibfk_1` FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE farm_health_scan RENAME INDEX idx_c32eec75a76ed395 TO user_id');
        $this->addSql('ALTER TABLE offre CHANGE description description VARCHAR(255) DEFAULT \'NULL\', CHANGE prix_mensuel prix_mensuel FLOAT NOT NULL, CHANGE avantages avantages TEXT DEFAULT NULL, CHANGE couleur_primaire couleur_primaire VARCHAR(20) DEFAULT \'\'\'#6B7F3F\'\'\', CHANGE couleur_secondaire couleur_secondaire VARCHAR(20) DEFAULT \'\'\'#4A5A2B\'\'\', CHANGE date_creation date_creation DATETIME DEFAULT \'current_timestamp()\'');
        $this->addSql('ALTER TABLE prevention_plan DROP FOREIGN KEY FK_873E4A574BD2A4C0');
        $this->addSql('ALTER TABLE prevention_plan CHANGE problem_summary problem_summary TEXT DEFAULT NULL, CHANGE steps steps TEXT NOT NULL, CHANGE estimated_cost estimated_cost FLOAT DEFAULT \'NULL\', CHANGE expected_outcome expected_outcome TEXT DEFAULT NULL, CHANGE impact_level impact_level ENUM(\'HIGH\', \'MEDIUM\', \'LOW\') DEFAULT \'NULL\', CHANGE status status ENUM(\'ACTIVE\', \'COMPLETED\', \'ABANDONED\') DEFAULT \'\'\'ACTIVE\'\'\', CHANGE start_date start_date DATE DEFAULT \'NULL\', CHANGE created_at created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL');
        $this->addSql('ALTER TABLE prevention_plan ADD CONSTRAINT `prevention_plan_ibfk_1` FOREIGN KEY (report_id) REFERENCES farm_health_report (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE prevention_plan RENAME INDEX idx_873e4a574bd2a4c0 TO report_id');
        $this->addSql('ALTER TABLE prevention_plan RENAME INDEX idx_873e4a5772897d8b TO vulnerability_id');
        $this->addSql('ALTER TABLE prevention_task DROP FOREIGN KEY FK_81ACA0FC44547A6');
        $this->addSql('ALTER TABLE prevention_task CHANGE status status ENUM(\'PENDING\', \'COMPLETED\', \'MISSED\') DEFAULT \'\'\'PENDING\'\'\', CHANGE proof_photo_url proof_photo_url VARCHAR(500) DEFAULT \'NULL\', CHANGE completed_at completed_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE prevention_task ADD CONSTRAINT `prevention_task_ibfk_1` FOREIGN KEY (prevention_plan_id) REFERENCES prevention_plan (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE prevention_task RENAME INDEX idx_81aca0fc44547a6 TO prevention_plan_id');
        $this->addSql('ALTER TABLE produits DROP FOREIGN KEY FK_BE2DDF8CFE6E88D7');
        $this->addSql('ALTER TABLE produits ADD device ENUM(\'TND\', \'EUR\', \'USD\') DEFAULT \'\'\'TND\'\'\', DROP remise, DROP typeRemise, CHANGE nom nom VARCHAR(255) NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE prix prix FLOAT NOT NULL, CHANGE quantiteStock quantiteStock INT DEFAULT 0 NOT NULL, CHANGE categorie categorie VARCHAR(100) NOT NULL, CHANGE uniteMesure uniteMesure ENUM(\'KG\', \'G\', \'L\', \'ML\', \'UNITE\', \'TONNE\') DEFAULT \'\'\'KG\'\'\', CHANGE image image VARCHAR(500) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE produits ADD CONSTRAINT `fk_produit_user` FOREIGN KEY (idUser) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX idx_produit_categorie ON produits (categorie)');
        $this->addSql('ALTER TABLE produits RENAME INDEX idx_be2ddf8cfe6e88d7 TO idx_produit_idUser');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6224CCA91');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6905FC057');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6C5568CE4');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6C44547A6');
        $this->addSql('DROP INDEX IDX_794381C6224CCA91 ON review');
        $this->addSql('DROP INDEX IDX_794381C6905FC057 ON review');
        $this->addSql('DROP INDEX IDX_794381C6C5568CE4 ON review');
        $this->addSql('DROP INDEX IDX_794381C6C44547A6 ON review');
        $this->addSql('ALTER TABLE review CHANGE review_type review_type ENUM(\'DIAGNOSIS\', \'PROGRESS\', \'PREVENTION\') NOT NULL, CHANGE status status ENUM(\'PENDING\', \'IN_PROGRESS\', \'COMPLETED\') DEFAULT \'\'\'PENDING\'\'\', CHANGE photo_url photo_url VARCHAR(500) DEFAULT \'NULL\', CHANGE ai_analysis ai_analysis TEXT DEFAULT NULL, CHANGE expert_notes expert_notes TEXT DEFAULT NULL, CHANGE expert_verdict expert_verdict ENUM(\'HEALED\', \'CONTINUE\', \'WORSENED\') DEFAULT \'NULL\', CHANGE expert_disease_name expert_disease_name VARCHAR(255) DEFAULT \'NULL\', CHANGE created_at created_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'current_timestamp()\' NOT NULL, CHANGE farmer_response farmer_response ENUM(\'ACCEPTED\', \'REJECTED\', \'ACKNOWLEDGED\') DEFAULT \'NULL\', CHANGE ai_proposed_plan ai_proposed_plan TEXT DEFAULT NULL, CHANGE diagnostic_id diagnostic_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE traitement DROP FOREIGN KEY FK_2A356D27224CCA91');
        $this->addSql('DROP INDEX IDX_2A356D27224CCA91 ON traitement');
        $this->addSql('ALTER TABLE traitement CHANGE description_detaillee description_detaillee TEXT DEFAULT NULL, CHANGE type_traitement type_traitement ENUM(\'FONGICIDE\', \'HERBICIDE\', \'INSECTICIDE\', \'BACTERICIDE\', \'NEMATICIDE\', \'VIRUCIDE\', \'NUTRIMENT\', \'REGULATEUR_CROISSANCE\', \'AUTRE\') DEFAULT \'\'\'AUTRE\'\'\', CHANGE duree_recommandee duree_recommandee VARCHAR(50) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE treatment_plan DROP FOREIGN KEY FK_1E99976C224CCA91');
        $this->addSql('ALTER TABLE treatment_plan ADD expert_advice TEXT DEFAULT NULL, ADD is_expert_verified TINYINT DEFAULT 0, ADD follow_up_image_url VARCHAR(255) DEFAULT \'NULL\', ADD review_type ENUM(\'DIAGNOSIS\', \'PLAN\') DEFAULT \'NULL\', CHANGE start_date start_date DATETIME DEFAULT \'current_timestamp()\', CHANGE status status ENUM(\'ACTIVE\', \'COMPLETED\', \'ABANDONED\', \'PENDING_EXPERT_REVIEW\') DEFAULT \'\'\'ACTIVE\'\'\'');
        $this->addSql('ALTER TABLE treatment_plan RENAME INDEX idx_1e99976c224cca91 TO diagnostic_id');
        $this->addSql('ALTER TABLE treatment_task DROP FOREIGN KEY FK_91BD1734905FC057');
        $this->addSql('ALTER TABLE treatment_task ADD image_path VARCHAR(500) DEFAULT \'NULL\', CHANGE status status ENUM(\'PENDING\', \'COMPLETED\', \'MISSED\') DEFAULT \'\'\'PENDING\'\'\', CHANGE tech_x tech_x DOUBLE PRECISION DEFAULT \'0\', CHANGE tech_y tech_y DOUBLE PRECISION DEFAULT \'0\'');
        $this->addSql('ALTER TABLE treatment_task RENAME INDEX idx_91bd1734905fc057 TO treatment_plan_id');
        $this->addSql('ALTER TABLE user ADD biometric_enabled TINYINT DEFAULT 0, DROP points_fidelite, CHANGE role role ENUM(\'ADMIN\', \'AGRICULTEUR\', \'CLIENT\', \'AGRONOME\') DEFAULT \'\'\'AGRICULTEUR\'\'\' NOT NULL, CHANGE points points INT DEFAULT 0, CHANGE level level INT DEFAULT 1, CHANGE two_factor_enabled two_factor_enabled TINYINT DEFAULT 0, CHANGE two_factor_code two_factor_code VARCHAR(10) DEFAULT \'NULL\', CHANGE two_factor_expires_at two_factor_expires_at DATETIME DEFAULT \'NULL\', CHANGE fingerprint_signature fingerprint_signature MEDIUMTEXT DEFAULT NULL, CHANGE reset_password_code reset_password_code VARCHAR(10) DEFAULT \'NULL\', CHANGE reset_password_expires_at reset_password_expires_at DATETIME DEFAULT \'NULL\', CHANGE phone phone VARCHAR(20) DEFAULT \'NULL\', CHANGE location location VARCHAR(255) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE vulnerability DROP FOREIGN KEY FK_6C4E40474BD2A4C0');
        $this->addSql('ALTER TABLE vulnerability CHANGE type type ENUM(\'PEST_OUTBREAK_RISK\', \'DISEASE_RISK\', \'NUTRIENT_DEFICIENCY\', \'LOW_POLLINATION\', \'SOIL_DEGRADATION\') NOT NULL, CHANGE severity severity ENUM(\'CRITICAL\', \'MEDIUM\', \'LOW\') NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE risk_score risk_score FLOAT DEFAULT \'NULL\', CHANGE estimated_cost_if_occurs estimated_cost_if_occurs FLOAT DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE vulnerability ADD CONSTRAINT `vulnerability_ibfk_1` FOREIGN KEY (report_id) REFERENCES farm_health_report (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vulnerability RENAME INDEX idx_6c4e40474bd2a4c0 TO report_id');
    }
}
